// @ts-check

/**
 * Canonical doctrine registry.
 * This file stores static meaning only (no live values, no compute logic).
 */
export const MODULE_DOCTRINE_REGISTRY = Object.freeze({
  targetingLab: Object.freeze({
    id: "targetingLab",
    title: "Targeting Lab",
    summary: "Rank geographies and targets with canonical targeting outputs before execution planning.",
    sections: Object.freeze({
      whatItIs: "A prioritization workspace that converts canonical model outputs into ranked field targets.",
      whenToUse: "Use when defining who to contact first, where to deploy organizers, and where to allocate limited attempts.",
      whenNotToUse: "Do not use as a replacement for validation, readiness, or realism checks.",
      feedsInto: "Feeds targetUniverseMatrix, optimizer, forecastOutcome, and warRoomDecisionSession.",
      parametersExplained: "Weights shape emphasis; they do not create a second math engine.",
      rangesExplained: "Weight ranges are relative priorities, not absolute probabilities.",
      howToThink: "Rank by expected strategic value per constrained unit of field capacity.",
      mathBehindIt: "Master targeting law v1: persuasionMultiplier=max(0,1-2*abs(0.5-supportScore)); adjustedPersuasion=persuasionIndex*persuasionMultiplier; baseScore=(voteWeight*votePotential)+(turnoutWeight*turnoutOpportunity)+(persuasionWeight*adjustedPersuasion)+(fieldWeight*fieldEfficiency)+(networkWeight*networkValue); targetScore=baseScore*contactProbability*geographicMultiplier*saturationMultiplier; expectedNetVoteValue=targetScore*expectedVotesReachable/costPerContact.",
      whatGoodLooksLike: "Top-ranked targets remain stable under modest assumption perturbations.",
      warningSigns: "Large ranking swings from tiny input edits indicate unstable assumptions.",
      adjustmentRules: "Adjust weighting only when doctrine-backed strategic objective changes.",
      origins: "Built from canonical targeting law and practical field prioritization constraints.",
      modelPhilosophy: "One architecture, many strategic emphases.",
    }),
    relatedModules: Object.freeze(["targetUniverseMatrix", "optimizer", "forecastOutcome"]),
    relatedModels: Object.freeze([
      "supportTurnoutMatrix",
      "congressionalTargetScore",
      "masterTargetingEquation",
      "expectedVoteGain",
      "contactSaturation",
      "geographicPersuasionClustering",
    ]),
    relatedTerms: Object.freeze(["variance", "lift", "contact probability", "saturation", "vote path"]),
  }),
  optimizer: Object.freeze({
    id: "optimizer",
    title: "Optimizer",
    summary: "Allocate finite budget and capacity across channels without violating canonical constraints.",
    sections: Object.freeze({
      whatItIs: "A constrained allocation layer consuming canonical conversion and cost outputs.",
      whenToUse: "Use when choosing between doors, calls, texts, mail, and lit drop tradeoffs.",
      whenNotToUse: "Do not use when readiness or validation blockers remain unresolved.",
      feedsInto: "Feeds forecastOutcome, budgetChannelCost, and warRoomDecisionSession.",
      parametersExplained: "Objective and constraints control tradeoffs, not formula architecture.",
      rangesExplained: "Channel costs and throughput bounds represent operational feasibility bands.",
      howToThink: "Maximize expected strategic value per constrained dollar and organizer hour.",
      mathBehindIt: "Uses canonical expected net vote value, capacity, and channel cost inputs.",
      whatGoodLooksLike: "Allocation reflects both cost efficiency and execution realism.",
      warningSigns: "Over-concentration in one low-cost channel with weak conversion confidence.",
      adjustmentRules: "Revise constraints and assumptions before forcing objective-only changes.",
      origins: "Resource optimization under campaign execution constraints.",
      modelPhilosophy: "Transparent constraint tradeoff, no hidden overrides.",
    }),
    relatedModules: Object.freeze(["budgetChannelCost", "turnoutContactSaturation", "forecastOutcome"]),
    relatedModels: Object.freeze(["votePathOptimization", "persuasionCost", "expectedVoteGain", "masterTargetingEquation"]),
    relatedTerms: Object.freeze(["cost per contact", "contact probability", "realism", "confidence"]),
  }),
  forecastOutcome: Object.freeze({
    id: "forecastOutcome",
    title: "Forecast Outcome",
    summary: "Turn current assumptions, evidence, and execution posture into an honest reading of where the campaign is likely headed and how much uncertainty surrounds that path.",
    sections: Object.freeze({
      whatItIs: "This is the campaign's outcome-reading layer. It is not here to flatter the team or produce one magic number. It is here to show the range of what is realistically on the table so decisions can be made with open eyes. In campaigns, that matters because the strongest plans are not built on the prettiest case. They are built on a believable middle, a survivable downside, and a clear understanding of how much upside is actually real.",
      whenToUse: "Use this panel during weekly reviews, pacing checks, leadership conversations, scenario comparisons, budget-pressure decisions, and any moment when the team needs to know not just whether the picture looks good, but whether it is strong enough to trust.",
      whenNotToUse: "Do not use this panel like a scoreboard. Do not point to the highest visible number and act as if it is the plan. Do not use a favorable top-end case to skip realism, readiness, or evidence review. The point is not to manufacture confidence. The point is to choose the right level of confidence for the decision in front of you.",
      feedsInto: "Feeds governanceConfidence, warRoomDecisionSession, scenario framing, and reporting language.",
      parametersExplained: "This forecast reflects the interaction of assumptions, execution pace, targeting quality, uncertainty spread, and evidence freshness. A forecast becomes more useful when the campaign is disciplined about what changed, why it changed, and whether the inputs underneath the story are still credible.",
      rangesExplained: "The live range shows P10, P50, and P90 from one forecast distribution. These are not different opinions. They are different points across the same modeled outcome spread. P10 is a cautious lower-tail case, P50 is the honest middle, and P90 is the aggressive upside edge. If additional cuts such as P30 or P70 are exposed later, read them as intermediate confidence points between floor and ceiling.",
      whatEachNumberMeans: "P10: protective planning floor when conditions run softer than expected | P50: honest middle and default planning anchor | P90: ceiling-side upside check, not baseline execution truth",
      whichNumberShouldYouUse: "Use P50 for standard planning, pacing, and ordinary expectation-setting. Use P10 when the cost of missing is high and commitments need protection. Use P90 for upside checks, contingency thinking, and ceiling-testing, not for routine promises or base staffing. If P30 and P70 are later surfaced, treat P30 as a safer planning number and P70 as realistic upside within reason.",
      whatGoodLooksLike: "A good range is not just a high one. A good range is strong enough to support the goal and stable enough to trust. If the middle of the forecast clears the target, that is healthy. If only the top-end case clears the target, the plan may be leaning too hard on upside. A strong outlook has a believable middle, a manageable downside, and movement that can be traced back to real changes in evidence or execution.",
      tightVsWideRanges: "A tight range usually means the signal is clearer, the assumptions are more aligned, and the planning environment is more stable. A wide range means uncertainty is still doing real work. That does not mean the opportunity is bad. It means the team should be more careful about overcommitting. A wide range is useful truth. It is the system's way of saying there may be upside here, but do not confuse possibility with certainty.",
      howToReadChange: "The first question is not 'What is the number?' It is 'What changed?' If the whole range rises together, that usually signals genuine strengthening. If only the top end rises, that may mean more upside volatility, not a stronger base. If the middle holds while the lower end weakens, the campaign may still look fine on the surface while becoming more fragile underneath. Not every larger number is better. Sometimes the steadier path is operationally stronger than the flashier one.",
      howToThink: "Teams should be explicit about planning off floor, middle, or upside. That simple discipline keeps strategy honest. It prevents aggressive bets from being sold as normal assumptions and keeps everyone aligned on what kind of plan they are actually choosing: safe, balanced, or aggressive.",
      oneMinuteExplanation: "This panel answers three questions fast. What is the most honest middle path? What does the downside look like if conditions soften? And how much of the story depends on upside? P50 is usually the best anchor for ordinary planning. Lower-tail cases protect commitments. Upper-tail cases show what is possible, not what should automatically be promised.",
      concreteExample: "Imagine the forecast shows P10 at 4,200, P50 at 5,000, and P90 at 6,300. If the campaign needs 4,800 to feel on track, that is encouraging because the honest middle clears the mark. But if the campaign needs 5,900, the picture changes. Now success depends on a more optimistic edge of the distribution. That may still be worth chasing, but the team should say plainly that the plan is no longer anchored in the middle case.",
      mathBehindIt: "The forecast starts from canonical expected-value outputs and then frames uncertainty around that center. Percentile cuts summarize the spread of plausible outcomes so the team can distinguish between a stable path, a fragile path, and a high-variance upside story.",
      warningSigns: "Watch for confidence-sounding language that gets stronger while the evidence stays flat. Watch for ranges widening without explanation. Watch for repeated reliance on top-end cases to justify baseline decisions. And watch for leadership conversations that treat the nicest number in the panel as if it were the campaign's default future.",
      adjustmentRules: "If only the upper end of the range supports the plan, say that plainly and tighten execution, scope, pacing, or resource posture before escalating commitments. If the lower-tail case becomes operationally intolerable, do not wait for hope to rescue the plan. Reduce exposure, revisit assumptions, or change the mix early.",
      origins: "Decision-support forecasting, not decorative charting.",
      modelPhilosophy: "Do not ask only how high the number is. Ask how dependable the path to it is. Honest uncertainty is more useful than false precision, especially when real resources, real people, and real campaign commitments sit on the other side of the decision.",
    }),
    relatedModules: Object.freeze(["governanceConfidence", "learningAudit", "warRoomDecisionSession"]),
    relatedModels: Object.freeze(["expectedVoteGain", "turnoutElasticity", "masterTargetingEquation"]),
    relatedTerms: Object.freeze(["confidence", "confidenceBand", "percentileRange", "median", "planningFloor", "upsideCase", "variance", "signal", "noise", "scenario drift"]),
  }),
  governanceConfidence: Object.freeze({
    id: "governanceConfidence",
    title: "Governance Confidence",
    summary: "Score how much trust the campaign should place in the current read of the model given evidence quality, freshness, coverage, and operational discipline.",
    sections: Object.freeze({
      whatItIs: "This is the trust layer. It does not tell you whether the output is flattering. It tells you how hard you should lean on it. In practice, that means it separates polished-looking output from genuinely trustworthy output.",
      whenToUse: "Use before major decisions, leadership briefs, external reporting, budget commitments, public-facing framing, and any time the campaign is about to act as if the current numbers deserve real confidence.",
      whenNotToUse: "Do not use confidence labels as cover for missing inputs, stale reporting, or unresolved contradictions. Confidence is not a branding layer. It is a warning system against pretending the campaign knows more than it actually does.",
      feedsInto: "Feeds readiness, war room framing, and reporting trust language.",
      parametersExplained: "Confidence reflects evidence quality, update cadence, provenance, coverage, consistency, and operational realism. The cleaner the reporting discipline, the more meaningful the confidence read becomes.",
      rangesExplained: "Low confidence does not automatically mean the model is broken. It means the team should commit more cautiously and speak more precisely about what is known, what is inferred, and what is still weakly evidenced. High confidence should be earned through discipline, not assumed because the interface looks polished.",
      howToThink: "A clean output is not the same as a trustworthy output. Confidence rises when the campaign can name the source of the evidence, the owner of the update, the cadence of the refresh, and the reason the system should believe the current picture. That is what keeps the campaign from sounding certain when it is actually guessing.",
      mathBehindIt: "Computed from canonical governance and validation aggregates.",
      whatGoodLooksLike: "Confidence moves for reasons the team can explain. Better evidence increases trust. Missing or stale required inputs lower it. The campaign can point to exactly why confidence improved or weakened instead of treating it like a mysterious background score.",
      warningSigns: "Confidence drifting upward while required data is missing. Leadership language becoming stronger than the evidence. Reports that look clean but are built on stale or thin source paths. Teams using polish as a substitute for disciplined reporting.",
      adjustmentRules: "When confidence weakens, reduce claim strength before you reduce honesty. Refresh evidence, re-establish provenance, and fix missing ownership before overriding the warning. If a decision is high-stakes, require stronger source discipline before acting as if the current output is settled truth.",
      origins: "Operational trust governance in campaign analytics workflows.",
      modelPhilosophy: "Trust is not granted because the model produced a number. Trust is earned when the campaign can show why that number deserves to be believed right now.",
    }),
    relatedModules: Object.freeze(["learningAudit", "scenarioManager", "forecastOutcome"]),
    relatedTerms: Object.freeze(["confidence", "confidenceBand", "percentileRange", "bias", "calibration", "signal", "noise"]),
  }),
  templateArchetype: Object.freeze({
    id: "templateArchetype",
    title: "Template Archetype",
    summary: "Set initial planning archetype by race context while preserving canonical engine architecture.",
    sections: Object.freeze({
      whatItIs: "A default profile system for initial assumptions and ranges.",
      whenToUse: "Use at campaign setup and when opening new scenario branches.",
      whenNotToUse: "Do not treat templates as final assumptions for late-cycle decisions.",
      feedsInto: "Feeds targetingLab, forecastOutcome, turnoutContactSaturation, and optimizer.",
      parametersExplained: "Template dimensions set default assumptions profile and benchmark scope.",
      rangesExplained: "Template ranges are starting priors; observed data should override over time.",
      howToThink: "Template first, then calibrate with campaign-specific evidence.",
      mathBehindIt: "No independent math; configures canonical model input defaults.",
      whatGoodLooksLike: "Template assumptions converge toward observed campaign behavior.",
      warningSigns: "Template defaults remain untouched despite contradictory field evidence.",
      adjustmentRules: "Document template overrides with rationale in governance notes.",
      origins: "Operational startup discipline for campaign modeling.",
      modelPhilosophy: "Faster setup without sacrificing explicit assumptions.",
    }),
    relatedModules: Object.freeze(["governanceConfidence", "scenarioManager", "learningAudit"]),
    relatedModels: Object.freeze(["turnoutElasticity"]),
    relatedTerms: Object.freeze(["calibration", "bias", "readiness"]),
  }),
  districtRaceContext: Object.freeze({
    id: "districtRaceContext",
    title: "District Reality / Race Context",
    summary: "Set the race frame honestly so every downstream assumption starts from believable context instead of cosmetic optimism.",
    sections: Object.freeze({
      whatItIs: "Templates and office context: Templates are operating presets. They do not tell the model what to believe. They give the system a realistic starting posture based on office type, contest context, and campaign environment. The template is not the answer. It is the opening frame. Good operators start from the closest honest context, then tighten or widen assumptions based on local evidence. The danger is not using a template. The danger is using the wrong one and forgetting what it quietly implies.",
      whenToUse: "Use this first when building or resetting a district model: set race template, election date, office level, election type, seat context, partisanship mode, and salience level before trusting downstream outputs.",
      whenNotToUse: "Do not treat race context as a cosmetic setup form. Do not pick a softer template just to make the path look easier. Do not leave election type or salience on defaults when the real contest environment is materially different.",
      feedsInto: "Feeds electorate framing, turnout baseline posture, ballot interpretation, targeting posture, reach assumptions, turnout expectations, forecast confidence framing, and war-room risk language.",
      parametersExplained: "Race template vs office level: Race template is the main preset package that sets starting planning posture and default values like persuasion and early vote expectations. Office level is contest context and uncertainty framing; it does not automatically rewrite numeric defaults unless defaults are re-applied. Election type (general/primary/special): use primary when the contest is intra-party or nomination-defining; use special when structurally unusual or accelerated; use general for normal general-election environments. Seat context: describe the actual strategic posture (open/incumbent/challenger/executive/legislative/statewide), not the title you wish the race had. Partisanship mode: use partisan when party identity materially structures the electorate; use nonpartisan when ballot structure and public framing do not behave like a standard party contest. Salience level: a judgment about how much attention, outside pressure, and narrative volatility the race is likely to carry. Use Low for quieter, more locally legible contests. Use Medium for normal competitive environments. Use High when the race is highly watched, heavily contested, or likely to absorb major media and spending pressure.",
      rangesExplained: "Office breakdown: Statewide Executive should be treated as broader and more uneven than district-sized races; coalition management, geography, vote mode, and message reach all become less uniform. Statewide Federal adds nationalized attention and outside influence, so apparent stability can break quickly. Congressional District races are usually more geographically legible than statewide races but can still become fragile under uniform-performance assumptions. State House and State Senate are often field-legible but can still break when district reality is misunderstood. Countywide races can vary sharply between municipal anchors, suburban rings, and lower-density precincts. Municipal Executive and Municipal Legislative races are local and field-legible but vulnerable to low-turnout irregularity and local shocks. Judicial / Other should default to a cautious posture and explicit operator judgment. Custom Context should be used only when the standard office frames do not fit the actual contest.",
      howToThink: "Set race context honestly, then calibrate with evidence. Ask: is this race mostly operating through local structure, or is it hot enough that outside pressure can quickly change conditions? Use nearest honest context first; adjust only when polling, local turnout behavior, operational evidence, or hard historical comparisons justify it.",
      mathBehindIt: "No deterministic formula change. This layer sets context metadata and default assumptions profile only; deterministic math, Monte Carlo behavior, and report logic remain unchanged.",
      whatGoodLooksLike: "A strong context setup is not just a label match. It is a race frame where template, office level, election type, seat context, partisanship, and salience all describe the real contest and where overrides are explainable from local evidence.",
      warningSigns: "Office risk flags: statewide executive plans can hide local weakness inside strong toplines, over-rely on one metro/media market, or import early-vote assumptions from the wrong context. Statewide federal plans can rely on favorable late movement, weak evidence refresh, or treat a media-driven race as if field execution alone stabilizes the map. District and county contexts can fail when composition variation is ignored. Cross-cutting warning: users think office level alone rewrites defaults and never verify whether race template still matches reality.",
      adjustmentRules: "Override defaults when local data, polling, historical turnout behavior, or operational evidence clearly support better assumptions. Do not override to make planning easier. If context is unusual, widen uncertainty, document rationale, and keep governance traceability.",
      origins: "District field-guide editorial pack, race-context office breakdown, and right-rail explainer relocation into manual doctrine.",
      modelPhilosophy: "Key assumptions should carry live planning values; interpretation and training belong in the manual layer.",
    }),
    relatedModules: Object.freeze([
      "templateArchetype",
      "districtElectorate",
      "districtTurnoutBaseline",
      "districtBallotLandscape",
      "districtTargetConfig",
      "operatorWorkflowGuide",
    ]),
    relatedModels: Object.freeze(["turnoutElasticity"]),
    relatedTerms: Object.freeze(["calibration", "confidenceBand", "variance", "readiness"]),
  }),
  districtElectorate: Object.freeze({
    id: "districtElectorate",
    title: "Electorate",
    summary: "Define the modeled voter universe correctly before trusting vote math, labor math, or pacing math.",
    sections: Object.freeze({
      whatItIs: "Electorate is the base-universe definition layer: universe size, basis, composition, and support retention.",
      whenToUse: "Use immediately after race context setup and before turnout, ballot interpretation, targeting, or plan translation.",
      whenNotToUse: "Do not treat electorate fields as rough placeholders. If universe size or basis is wrong, downstream precision is fake precision.",
      feedsInto: "Feeds turnout baseline votes, persuasion universe, reach pressure, turnout lift interpretation, outcome range framing, and plan staffing math.",
      parametersExplained: "Universe size (U): number of voters in the relevant modeled base; if inflated, labor and vote estimates become falsely optimistic. Universe basis: keep the same basis across turnout, targeting, and reporting. Weighted electorate composition: enable only when you can justify explicit composition framing. Dem/Rep/Unaffiliated/Other shares: descriptive grounding, not a substitute for direct support estimates. Support retention (0.60-0.95): manual planning assumption for the share of identified support expected to hold through Election Day. Treat it as aggregate planning posture, not CRM-level discovered truth. Raise only when coalition stability is unusually strong; lower when support is soft, irregular, or vulnerable to drop-off.",
      rangesExplained: "Retention and composition are uncertainty controls, not comfort controls. In practice, many races sit around 0.70-0.90 retention. Conservative settings widen planning discipline; aggressive settings should require stronger evidence quality.",
      howToThink: "The electorate is a truth constraint. Build from the most defensible base first, then adjust with evidence rather than narrative preference.",
      mathBehindIt: "No new formulas; this module sets canonical electorate inputs consumed by existing deterministic and Monte Carlo paths.",
      whatGoodLooksLike: "Universe basis is consistent, source note is clear, and retention assumptions match observed coalition stability.",
      warningSigns: "Inflated universe size, inconsistent basis across modules, composition toggled on without rationale, and retention raised without evidence.",
      adjustmentRules: "When evidence weakens, lower retention assumptions before escalating capacity claims. Document source and vintage when changing universe size or basis.",
      origins: "Module-by-module field guide: Electorate section and in-app copy snippets for support retention.",
      modelPhilosophy: "If the electorate is wrong, every downstream answer can look precise while being directionally wrong.",
    }),
    relatedModules: Object.freeze([
      "districtRaceContext",
      "districtTurnoutBaseline",
      "districtBallotLandscape",
      "reachOperationsGuide",
    ]),
    relatedTerms: Object.freeze(["persuasionUniverse", "mobilizationUniverse", "confidenceBand", "calibration"]),
  }),
  districtTurnoutBaseline: Object.freeze({
    id: "districtTurnoutBaseline",
    title: "Turnout Baseline",
    summary: "Anchor turnout environment with credible cycle history and explicit uncertainty spread.",
    sections: Object.freeze({
      whatItIs: "Turnout baseline sets historical turnout anchors and uncertainty band width for the modeled turnout environment.",
      whenToUse: "Use after electorate grounding and before ballot stress, targeting interpretation, and turnout-lift planning.",
      whenNotToUse: "Do not tighten uncertainty just to produce a cleaner leadership story.",
      feedsInto: "Feeds expected turnout, votes-per-point context, turnout module lift interpretation, outcome volatility framing, and plan risk posture.",
      parametersExplained: "Turnout cycle A / Turnout cycle B: historical anchors used to bracket likely turnout conditions; choose relevant cycles, not convenient cycles. Band width (plus/minus): uncertainty spread around turnout environment. Widen for volatile, uneven, or weakly understood environments. Narrow only when stability is unusually strong and evidence-backed.",
      rangesExplained: "Band width should reflect environment quality. Wider bands indicate real uncertainty and should moderate over-commitment; narrower bands should be earned through strong comparable evidence and disciplined reporting.",
      howToThink: "Use turnout history to bound plausibility, not to manufacture confidence. Honest uncertainty is operationally useful.",
      mathBehindIt: "Uses existing turnout baseline and uncertainty inputs; no deterministic or Monte Carlo semantics are altered.",
      whatGoodLooksLike: "Chosen cycles are comparable, band width is evidence-driven, and turnout assumptions remain stable unless new evidence warrants change.",
      warningSigns: "Cycles chosen for convenience, band narrowed without evidence, and leadership treating one turnout environment as guaranteed.",
      adjustmentRules: "If comparability weakens or volatility rises, widen the band early. If evidence quality improves materially, tighten gradually and document why.",
      origins: "Module-by-module field guide: Turnout Baseline and in-app Band width authored snippet.",
      modelPhilosophy: "Treat turnout uncertainty as decision discipline, not presentation noise.",
    }),
    relatedModules: Object.freeze([
      "districtElectorate",
      "districtBallotLandscape",
      "turnoutOperationsGuide",
      "outcomeOperationsGuide",
    ]),
    relatedTerms: Object.freeze(["turnoutOpportunity", "confidenceBand", "variance"]),
  }),
  districtBallotLandscape: Object.freeze({
    id: "districtBallotLandscape",
    title: "Ballot / Vote Landscape",
    summary: "Set candidate frame and undecided handling with discipline so the path reflects real coalition structure.",
    sections: Object.freeze({
      whatItIs: "Ballot / vote landscape defines focal candidate identity, candidate set, undecided share, and undecided allocation mode.",
      whenToUse: "Use after turnout baseline setup and before targeting and reach assumptions are finalized.",
      whenNotToUse: "Do not use undecided handling to engineer comfort. Do not leave candidate definitions stale after major ballot changes.",
      feedsInto: "Feeds persuasion need framing, target universe prioritization, reach pressure, turnout strategy, outcome distribution, and plan workload estimates.",
      parametersExplained: "You are: the focal candidate in the model. Undecided percent: share of vote not yet allocated. Undecided break: allocation method for undecided votes. Use restrained assumptions; reflect real strategic environment instead of manufacturing a friendly path.",
      rangesExplained: "Undecided assumptions are volatility controls. Aggressive breaks increase fragility when evidence quality is low.",
      howToThink: "Clarify who the campaign is, who else is on the ballot, and how uncertainty is handled before trusting downstream path math.",
      mathBehindIt: "No formula rewrite. This module sets canonical ballot-state inputs for existing deterministic and simulation outputs.",
      whatGoodLooksLike: "Candidate identities are current, totals are internally coherent, and undecided mode is evidence-aware.",
      warningSigns: "Undecided break drifts toward convenience, candidate rows stale, or support totals imply hidden contradictions.",
      adjustmentRules: "When undecided behavior is uncertain, stress-test against the campaign and keep source notes for why an allocation mode was chosen.",
      origins: "Module-by-module field guide: Ballot / Vote Landscape section.",
      modelPhilosophy: "Ballot clarity prevents downstream planning from being anchored to fictional coalition assumptions.",
    }),
    relatedModules: Object.freeze([
      "districtTurnoutBaseline",
      "districtTargetConfig",
      "reachOperationsGuide",
      "outcomeOperationsGuide",
    ]),
    relatedTerms: Object.freeze(["persuasion", "median", "planningFloor", "confidenceBand"]),
  }),
  districtTargetConfig: Object.freeze({
    id: "districtTargetConfig",
    title: "Target Config",
    summary: "Translate race context into operational turf ranking settings that match real field constraints.",
    sections: Object.freeze({
      whatItIs: "Target Config controls ranking geography level, model mode, rank filters, and weighting priorities for turf selection.",
      whenToUse: "Use only after ACS rows, GEO selection, race footprint, and baseline district setup are coherent.",
      whenNotToUse: "Do not run targeting on half-prepared geography context or before Data/Census reconciliation is complete.",
      feedsInto: "Feeds ranked GEO outputs, reach strategy, turnout execution mix, plan workload shaping, and war-room decision options.",
      parametersExplained: "Geography level: choose the unit the operation can actually execute against. Target model: choose objective match (persuasion, turnout opportunity, efficiency, or blend). Top N: number of highest-ranked geographies returned. Increase Top N for broader menu and backup turf; decrease for tighter focus and cleaner pilots. Minimum score: floor to appear in ranked list. Raise for higher-confidence cut; lower for more volume or backups. Density floor: minimum density requirement. Raise when walk efficiency matters; lower when lower-density areas are still strategic. Minimum housing units / minimum population: exclude tiny low-operational-value geographies. Only race footprint: should usually remain on outside exploratory analysis. Vote potential / turnout opportunity / persuasion index / field efficiency weights: prioritization levers, not a checklist to maximize simultaneously.",
      rangesExplained: "Rank controls trade focus against breadth. A larger turf list can look comprehensive while pushing the program into weaker units; tighter filters improve efficiency but can reduce backup depth.",
      howToThink: "Decide what problem you are solving before touching weights. Do not max every attractive metric; make explicit tradeoffs.",
      mathBehindIt: "Uses canonical targeting law and filters only; no secondary scoring engine is introduced.",
      whatGoodLooksLike: "Ranking is stable under modest perturbations, aligned to real field geometry, and explainable to operators.",
      warningSigns: "Top N inflated by default, minimum score dropped without rationale, density floor mismatched to operation, or weight changes made to chase preferred outputs.",
      adjustmentRules: "Tighten controls when focus and quality matter; loosen only when volume needs are real and operationally justified.",
      origins: "Module-by-module field guide: Target Config plus in-app snippets for Top N, Minimum score, and Density floor.",
      modelPhilosophy: "A mathematically strong rank is still wrong if the field program cannot execute it.",
    }),
    relatedModules: Object.freeze([
      "districtRaceContext",
      "districtElectorate",
      "targetingLab",
      "reachOperationsGuide",
      "operatorWorkflowGuide",
    ]),
    relatedTerms: Object.freeze(["saturation", "contact probability", "persuasionUniverse", "actionability"]),
  }),
  reachOperationsGuide: Object.freeze({
    id: "reachOperationsGuide",
    title: "Reach",
    summary: "Estimate how much contact volume is plausible, and separate capacity reality from optimistic assumptions.",
    sections: Object.freeze({
      whatItIs: "Reach estimates contactable volume and influenceable scope under current capacity and conversion assumptions.",
      whenToUse: "Use after Target Config when translating ranked targets into practical contact pressure and weekly throughput expectations.",
      whenNotToUse: "Do not use Reach to compensate for weak electorate grounding or unresolved targeting context.",
      feedsInto: "Feeds turnout execution, outcome confidence framing, plan workload requirements, and war-room feasibility calls.",
      parametersExplained: "Movable universe percent: share of universe realistically reachable or influenceable. Raise only when channel access and capacity are unusually strong; lower when contactability is constrained. Early vote expected percent: share likely to arrive before Election Day; set from actual state/race environment, not generic intuition. Support rate / contact rate: conversion assumptions linking attempts to supportive outcomes. Keep these grounded; do not drift upward because the plan feels hard.",
      rangesExplained: "Higher reach assumptions lower apparent labor burden but increase fragility when execution underperforms. Conservative assumptions provide safer planning floors.",
      howToThink: "Reach answers volume feasibility. Keep it distinct from turnout-lift effectiveness.",
      mathBehindIt: "No change to canonical reach equations; guidance only interprets existing assumptions.",
      whatGoodLooksLike: "Required weekly attempts are achievable under observed pace and assumptions are periodically calibrated to real logs.",
      warningSigns: "Movable universe inflated without channel evidence, early vote borrowed from non-comparable contexts, or rates rising while observed performance is flat.",
      adjustmentRules: "If observed execution trails assumptions, align assumptions to reality or increase capacity inputs before promising output growth.",
      origins: "Module-by-module field guide: Reach section and in-app Early vote expected authored snippet.",
      modelPhilosophy: "Separate reachable volume from desired outcomes to avoid planning illusions.",
    }),
    relatedModules: Object.freeze([
      "districtTargetConfig",
      "turnoutOperationsGuide",
      "outcomeOperationsGuide",
      "planOperationsGuide",
    ]),
    relatedTerms: Object.freeze(["capacity", "contact probability", "readiness", "confidenceBand"]),
  }),
  turnoutOperationsGuide: Object.freeze({
    id: "turnoutOperationsGuide",
    title: "Turnout",
    summary: "Model turnout lift conservatively with diminishing returns and tactic realism instead of linear optimism.",
    sections: Object.freeze({
      whatItIs: "Turnout module translates baseline turnout conditions and contact mechanics into plausible turnout movement.",
      whenToUse: "Use after Reach to test how contact volume converts to turnout gains under realistic constraints.",
      whenNotToUse: "Do not assume repeated contact keeps producing linear gains; do not enable tactics that are not operationally active.",
      feedsInto: "Feeds outcome risk posture, plan timeline pressure, and war-room recommendations on operating shifts.",
      parametersExplained: "Baseline turnout rate percent: pre-program turnout environment. Target-universe turnout override: use only with evidence that target universe behaves differently from baseline. GOTV lift model and diminishing returns: define how contact translates into turnout and where marginal gains flatten. Lift per contact / max lift ceiling / lift min-mode-max: set plausible lift bounds; stay conservative absent strong evidence. Tactic toggles (doors, phones, texts, lit drop, mail): enable only when truly part of program. Cost per attempt and tactic-level contact/support overrides: use when tactic performance materially differs from program defaults.",
      rangesExplained: "Lift bounds are risk posture tools. Aggressive ceilings widen downside exposure when field quality or contactability is uncertain.",
      howToThink: "Turnout is about plausibility under execution constraints, not a dial to force desired vote movement.",
      mathBehindIt: "No model rewrite; this guide interprets existing turnout lift and saturation mechanics.",
      whatGoodLooksLike: "Incremental gains taper realistically, enabled tactics match real operations, and lift assumptions are evidence-traceable.",
      warningSigns: "All tactics on by default, ceilings raised without evidence, or repeated-touch assumptions remain linear in late-cycle pressure.",
      adjustmentRules: "Lower lift before claiming more volume if evidence is weak. Add rationale when changing tactic overrides that materially affect outcomes.",
      origins: "Module-by-module field guide: Turnout section.",
      modelPhilosophy: "Conservative lift assumptions protect decisions from late-cycle overconfidence.",
    }),
    relatedModules: Object.freeze([
      "reachOperationsGuide",
      "outcomeOperationsGuide",
      "planOperationsGuide",
      "warRoomOperationsGuide",
    ]),
    relatedTerms: Object.freeze(["turnoutElasticity", "saturation", "confidenceBand", "planningFloor"]),
  }),
  outcomeOperationsGuide: Object.freeze({
    id: "outcomeOperationsGuide",
    title: "Outcome",
    summary: "Use outcome settings to reveal fragility and execution dependencies, not to manufacture certainty.",
    sections: Object.freeze({
      whatItIs: "Outcome combines staffing throughput assumptions, simulation posture, and reliability framing into a risk-aware path view.",
      whenToUse: "Use after Reach and Turnout are grounded to pressure-test path strength and fragility.",
      whenNotToUse: "Do not use Monte Carlo settings to chase a comforting win probability; use them to expose uncertainty honestly.",
      feedsInto: "Feeds plan commitment level, scenario branching decisions, war-room posture, and confidence language in reporting.",
      parametersExplained: "Organizers / organizer hours / volunteer multiplier: converts staffing into production capacity. Door share percent / doors per hour / calls per hour: define throughput profile. Monte Carlo mode / seed / volatility / run count: simulation posture controls; use for robustness checks, not presentation tuning. Turnout reliability percent: trust in turnout and execution assumptions. Target win percent: risk threshold, not a wish.",
      rangesExplained: "Higher volatility widens plausible spread; lower volatility without evidence can hide downside. Reliability should track source quality and execution discipline.",
      howToThink: "Outcome is a risk lens. Treat upper-tail outcomes as upside checks, not baseline commitments.",
      mathBehindIt: "No deterministic or Monte Carlo algorithm changes; this module documents interpretation and operator usage.",
      whatGoodLooksLike: "Middle-case and downside are decision-usable, and shifts in output can be explained by real input or execution changes.",
      warningSigns: "Win language strengthens while evidence is flat, volatility narrowed without justification, or staffing assumptions exceed observed pace.",
      adjustmentRules: "When downside becomes operationally intolerable, reduce exposure early: revise assumptions, capacity, or mix before escalating commitments.",
      origins: "Module-by-module field guide: Outcome section plus existing forecast governance doctrine.",
      modelPhilosophy: "Outcome should improve judgment by making uncertainty explicit.",
    }),
    relatedModules: Object.freeze([
      "forecastOutcome",
      "reachOperationsGuide",
      "turnoutOperationsGuide",
      "planOperationsGuide",
      "warRoomOperationsGuide",
    ]),
    relatedTerms: Object.freeze(["percentileRange", "median", "planningFloor", "upsideCase", "confidenceBand"]),
  }),
  planOperationsGuide: Object.freeze({
    id: "planOperationsGuide",
    title: "Plan",
    summary: "Translate grounded assumptions into labor, staffing, budget, and timeline commitments the field can actually execute.",
    sections: Object.freeze({
      whatItIs: "Plan is the translation layer from modeled vote path into workload, staffing, and budget requirements.",
      whenToUse: "Use after Reach, Turnout, and Outcome are coherent; this is where grounded strategy becomes executable workload.",
      whenNotToUse: "Do not use Plan as a substitute for weak upstream assumptions. If inputs are unstable, planning outputs are unstable.",
      feedsInto: "Feeds weekly execution targets, resource allocation choices, scenario comparisons, and war-room operating decisions.",
      parametersExplained: "Support IDs needed (goal): target identified-support production. Doors per hour / hours per shift / shifts per volunteer per week: labor translation controls and must match field reality. Optimize for / timeline objective / budget / step size: optimization posture controls. Timeline constrained and diminishing returns: realism constraints that prevent fantasy throughput. Paid field staff / volunteer hours / ramp shape: defines capacity growth profile over time.",
      rangesExplained: "Aggressive pace assumptions can create brittle plans that fail under normal variance. Conservative pace assumptions may appear slower but are often more survivable.",
      howToThink: "Plan is not where you discover the race. It is where you commit resources against a grounded model.",
      mathBehindIt: "Uses existing optimizer and workload math; no formula or report behavior changes.",
      whatGoodLooksLike: "Plan requirements align with observed pace, staffing reality, and risk posture selected in Outcome.",
      warningSigns: "Plan depends on idealized speed metrics, ignores diminishing returns, or assumes ramp growth unsupported by staffing signals.",
      adjustmentRules: "If execution is off-pace, first align assumptions or capacity. Do not simply raise goals without closing throughput constraints.",
      origins: "Module-by-module field guide: Plan section and workflow guide step ordering.",
      modelPhilosophy: "Operationally credible plans beat visually impressive plans.",
    }),
    relatedModules: Object.freeze([
      "optimizer",
      "reachOperationsGuide",
      "turnoutOperationsGuide",
      "outcomeOperationsGuide",
      "scenarioOperationsGuide",
    ]),
    relatedTerms: Object.freeze(["capacity", "actionability", "planningFloor", "confidence"]),
  }),
  dataOperationsGuide: Object.freeze({
    id: "dataOperationsGuide",
    title: "Data",
    summary: "Treat Data as intake, storage discipline, and audit reliability layer, not just file upload.",
    sections: Object.freeze({
      whatItIs: "Data module governs imports, external storage handling, archived reads, actuals, and audit notes that support trustworthy modeling.",
      whenToUse: "Use first when loading external files, archived forecasts, reconciliation files, ZIP overlays, or large Census bundles.",
      whenNotToUse: "Do not delay Data intake until after assumptions are tuned. Upstream data handling errors will contaminate every downstream interpretation.",
      feedsInto: "Feeds District setup integrity, Census/GEO readiness, targeting quality, governance confidence, reporting trust, and post-election audit quality.",
      parametersExplained: "Voter file / adapter / source ID: identifies source structure and provenance. Report type / archived forecast / actuals / result date / audit notes: supports post-election reconciliation and accountability. External storage handling: connect USB/external media for large bundles, verify files open outside app, keep one canonical bundle, avoid mid-stream renames, and capture source/vintage in notes.",
      rangesExplained: "Data quality and freshness determine how narrow confidence can reasonably be across the system.",
      howToThink: "If data intake is weak, model confidence should remain constrained no matter how polished outputs look.",
      mathBehindIt: "No model-math mutation; this layer controls source quality, reproducibility, and operational trust.",
      whatGoodLooksLike: "Imports are traceable, storage workflow is stable, and every critical input has source, owner, and timestamp context.",
      warningSigns: "Large bundle mismatches, missing source notes, duplicated file variants, and downstream outputs that drift without a clear upstream change.",
      adjustmentRules: "When data provenance weakens, reduce confidence language first, then restore data discipline before escalating decisions.",
      origins: "Workflow guide steps 2-3 and module-by-module Data section.",
      modelPhilosophy: "Reliable decisions start with reliable intake, not post-hoc interpretation.",
    }),
    relatedModules: Object.freeze([
      "campaignDataRequirements",
      "districtRaceContext",
      "districtTargetConfig",
      "operatorWorkflowGuide",
      "controlsOperationsGuide",
    ]),
    relatedTerms: Object.freeze(["readiness", "confidenceBand", "calibration", "scenarioDrift"]),
  }),
  mapOperationsGuide: Object.freeze({
    id: "mapOperationsGuide",
    title: "Campaign Geography Map",
    summary: "Operate Map stage as a field geography surface: Mapbox renders canonical boundaries and display-only overlays without mutating campaign canon.",
    sections: Object.freeze({
      whatItIs: "Map stage is a rendering and inspection surface for canonical geography context. Mapbox is used for browser visualization only; it is not a second analytics engine.",
      whenToUse: "Use after campaign, office, and geography context are selected to inspect boundaries, compare map-safe metrics, and review area-level field context.",
      whenNotToUse: "Do not treat map color as standalone truth. Do not infer new campaign math from map visuals. Do not store Mapbox token in scenario data.",
      feedsInto: "Feeds operator interpretation, district context checks, and area-level planning discussion while preserving existing deterministic planning outputs.",
      parametersExplained: "Mapbox token requirement: browser uses only a public token starting with pk. Configure it in Controls > Map configuration. Choropleth selector: display-only metric bundle choice. Fit/reset controls: viewport utility only. Area inspect: bounded context details for selected geography. Worked geography mode: joined turfEvents activity evidence for selected organizer/office scope, not inferred assignment turf.",
      rangesExplained: "Choropleth intensity is a relative visualization scale for the current geography selection; it does not change canonical calculations or campaign forecast posture.",
      howToThink: "Read this map as an operational lens over existing canon. Ask what geography context it clarifies, then confirm decisions against core model surfaces. Distinguish office context (scope footprint) from worked geography (logged activity evidence).",
      mathBehindIt: "No model math mutation. Map stage consumes canonical rows and geography context, then renders them through bounded display transforms.",
      whatGoodLooksLike: "Token configured once at app level, base map loads consistently, boundaries match canon context, and inspect panel provides useful field interpretation.",
      warningSigns: "Missing/invalid token, map boot failure, absent geometry for selected context, metric data gaps presented as certainty, or worked geography interpreted as assignment turf.",
      adjustmentRules: "When map context is incomplete, pause interpretation and resolve token/geography readiness first. Keep metric provenance explicit and treat map as display-only.",
      origins: "Map stage product hardening phases with app-level token governance, canonical geography overlay, and bounded inspect/legend behavior.",
      modelPhilosophy: "Map visuals should increase field clarity without introducing hidden compute paths or schema drift.",
    }),
    relatedModules: Object.freeze([
      "districtRaceContext",
      "districtTargetConfig",
      "dataOperationsGuide",
      "controlsOperationsGuide",
      "durabilityTrustStandards",
    ]),
    relatedTerms: Object.freeze([
      "geographyLevelField",
      "geoUnitsField",
      "sourceNoteField",
      "readiness",
      "confidence",
      "actionability",
    ]),
  }),
  controlsOperationsGuide: Object.freeze({
    id: "controlsOperationsGuide",
    title: "Controls",
    summary: "Use governance controls to keep major assumption changes auditable, disciplined, and decision-safe.",
    sections: Object.freeze({
      whatItIs: "Controls is the governance layer for scenario locks, evidence requirements, benchmark discipline, and advanced realism toggles.",
      whenToUse: "Use when coordinating high-stakes reviews, preserving comparability, and ensuring critical edits carry rationale and evidence.",
      whenNotToUse: "Do not treat controls as bureaucracy to bypass when pressure rises; that is when governance is most necessary.",
      feedsInto: "Feeds confidence posture, report trust language, scenario comparability, and war-room escalation discipline.",
      parametersExplained: "Scenario lock: freeze comparable state. Critical note/rationale/evidence required: force explainable trails for high-impact changes. Benchmark scope/default/range/warning/hard thresholds: set discipline around assumptions and expected bounds. Advanced controls (distribution choices, correlated shocks, capacity decay, shock scenarios): represent uncertainty better, not to cosmetically sophisticate outputs.",
      rangesExplained: "Stronger governance narrows interpretation risk even when modeled uncertainty remains wide.",
      howToThink: "Governance is operational risk control. It protects decisions from silent drift and undocumented override behavior.",
      mathBehindIt: "No math mutation; this module constrains process quality and interpretability.",
      whatGoodLooksLike: "Critical changes are traceable, lock state is used intentionally, and benchmark warnings drive explicit follow-up.",
      warningSigns: "Major edits without notes/evidence, frequent unlock-relock churn with no rationale, and threshold warnings ignored in leadership framing.",
      adjustmentRules: "If governance discipline weakens, reduce decision confidence until traceability is restored.",
      origins: "Module-by-module Controls section and existing durability doctrine.",
      modelPhilosophy: "Trust is maintained by process integrity, not just by output polish.",
    }),
    relatedModules: Object.freeze([
      "durabilityTrustStandards",
      "campaignDataRequirements",
      "scenarioOperationsGuide",
      "warRoomOperationsGuide",
    ]),
    relatedTerms: Object.freeze(["confidence", "readiness", "calibration", "bias"]),
  }),
  scenarioOperationsGuide: Object.freeze({
    id: "scenarioOperationsGuide",
    title: "Scenarios",
    summary: "Compare credible strategic paths without using scenarios to hide a weak base model.",
    sections: Object.freeze({
      whatItIs: "Scenarios is controlled branch analysis for comparing materially different but credible strategy options.",
      whenToUse: "Use after base model coherence is established and when leadership needs explicit tradeoff comparisons.",
      whenNotToUse: "Do not use scenarios to create fake optionality around unresolved setup problems.",
      feedsInto: "Feeds war-room decisions, plan commitments, reporting narratives, and post-decision accountability.",
      parametersExplained: "Scenario names, baseline comparison, and documented deltas should map to explicit assumption or policy differences.",
      rangesExplained: "Scenario spreads are only informative when branch differences are explicit and evidence-backed.",
      howToThink: "Branch cleanly, compare honestly, and keep each scenario tied to a real decision question.",
      mathBehindIt: "Scenarios reuse canonical compute paths; no duplicate formula stack.",
      whatGoodLooksLike: "Differences are explainable, high-impact, and decision-relevant.",
      warningSigns: "Many scenarios with vague differences, repeated preference for optimistic branches, and no documented decision linkage.",
      adjustmentRules: "If base-case coherence is weak, pause branching and repair core assumptions first.",
      origins: "Workflow guide and module-by-module Scenarios usage guidance.",
      modelPhilosophy: "Scenario breadth is useful only when branch quality stays disciplined.",
    }),
    relatedModules: Object.freeze([
      "scenarioManager",
      "planOperationsGuide",
      "warRoomOperationsGuide",
      "controlsOperationsGuide",
    ]),
    relatedTerms: Object.freeze(["scenarioDrift", "signal", "noise", "materialChange"]),
  }),
  warRoomOperationsGuide: Object.freeze({
    id: "warRoomOperationsGuide",
    title: "War Room",
    summary: "Use War Room for leadership decision framing after model coherence, not for basic setup repair.",
    sections: Object.freeze({
      whatItIs: "War Room converts a coherent analytical path into decision-ready operating choices.",
      whenToUse: "Use after District, Reach, Turnout, Outcome, and Plan are coherent, especially during high-pressure operating windows.",
      whenNotToUse: "Do not use War Room to paper over unresolved setup gaps or to quietly rewrite long-run assumptions.",
      feedsInto: "Feeds leadership posture, deployment timing, escalation level, and short-horizon operating actions.",
      parametersExplained: "War Room is interpretation and commitment framing: what changed, how trusted it is, and what action follows.",
      rangesExplained: "Decision posture should map to both movement magnitude and trust quality, not headline volatility alone.",
      howToThink: "District builds the analytical path; War Room converts that path into decision-ready choices.",
      mathBehindIt: "Consumes canonical outputs from forecast, plan, governance, and event signals without changing model semantics.",
      whatGoodLooksLike: "Recommendations are explicit, date-bound, and matched to confidence level and operational constraints.",
      warningSigns: "Leadership anchors on upside case, action escalates without confidence support, or short-term disruptions are used to justify long-term assumption drift.",
      adjustmentRules: "If evidence is noisy, narrow claims before widening commitments. Preserve clear follow-through ownership.",
      origins: "Workflow guide step 12 and module-by-module War Room guidance.",
      modelPhilosophy: "Decision speed is valuable only when assumptions and trust posture remain explicit.",
    }),
    relatedModules: Object.freeze([
      "warRoomDecisionSession",
      "forecastOutcome",
      "planOperationsGuide",
      "controlsOperationsGuide",
      "organizerOperationsWorkflow",
    ]),
    relatedTerms: Object.freeze(["actionability", "planningFloor", "upsideCase", "confidenceBand"]),
  }),
  organizerOperationsWorkflow: Object.freeze({
    id: "organizerOperationsWorkflow",
    title: "Organizer / Operations Workflow",
    summary: "Keep model assumptions grounded in observed field activity through disciplined organizer logging and weekly refresh cadence.",
    sections: Object.freeze({
      whatItIs: "Organizer workflow connects daily field execution updates to weekly model refresh and decision posture.",
      whenToUse: "Use continuously during campaign operations, with explicit update checkpoints before weekly model review.",
      whenNotToUse: "Do not let operations logging lag while assumptions continue to tighten or capacity claims continue to rise.",
      feedsInto: "Feeds reach calibration, turnout realism, outcome confidence, plan feasibility, and war-room recommendation quality.",
      parametersExplained: "Organizer log captures practical execution signals that should update capacity and rate assumptions before major planning decisions.",
      rangesExplained: "Fresh operations data narrows uncertainty; stale operations inputs keep confidence constrained.",
      howToThink: "A planning engine is only as honest as the execution data feeding it.",
      mathBehindIt: "No direct formula changes; operational inputs recalibrate assumptions through existing mechanisms.",
      whatGoodLooksLike: "Operations updates precede weekly review and materially explain assumption adjustments.",
      warningSigns: "Assumptions drift while organizer logs are stale, or staffing confidence rises without observed throughput support.",
      adjustmentRules: "When execution underperforms assumptions, update assumptions or capacity before committing to stronger claims.",
      origins: "Module-by-module Operations / Organizer workflow section.",
      modelPhilosophy: "Observed execution should discipline planning assumptions continuously.",
    }),
    relatedModules: Object.freeze([
      "operationsWorkforce",
      "reachOperationsGuide",
      "planOperationsGuide",
      "warRoomOperationsGuide",
      "operatorWorkflowGuide",
    ]),
    relatedTerms: Object.freeze(["capacity", "signal", "calibration", "confidence"]),
  }),
  operatorWorkflowGuide: Object.freeze({
    id: "operatorWorkflowGuide",
    title: "Operator Workflow Guide",
    summary: "Follow a safe usage order so downstream modules are interpreted on grounded context instead of stale or partial setup.",
    sections: Object.freeze({
      whatItIs: "End-to-end workflow guide for using the platform in the safest order: decide task, ground data, establish context, then translate to execution and decisions.",
      whenToUse: "Use at onboarding, first-pass district setup, targeting days, weekly check-ins, and pre-war-room reviews.",
      whenNotToUse: "Do not mix all jobs at once. Do not start by tweaking assumptions before deciding what question you are solving.",
      feedsInto: "Feeds reliable module sequencing across District, Data, Targeting, Reach, Turnout, Outcome, Plan, Scenarios, and War Room.",
      parametersExplained: "Recommended workflow order: Step 1 decide objective for today's session. Step 2 go to Data first if loading external files. Step 3 use external storage for large Census or overlay bundles. Step 4 set race context honestly. Step 5 define electorate before trusting vote math. Step 6 ground turnout baseline. Step 7 set ballot/vote landscape. Step 8 configure targeting only after ACS rows, GEOs, and footprint are ready. Step 9 build Reach and Turnout assumptions separately. Step 10 use Outcome for risk, not false certainty. Step 11 use Plan after path is grounded. Step 12 move to Scenarios and War Room only after model coherence.",
      rangesExplained: "Workflow discipline narrows interpretation error more than any single control tweak. Skipping early grounding steps widens downstream uncertainty and decision risk.",
      howToThink: "Do not rank turf before ACS rows and GEOs are loaded. Do not trust vote movement outputs before footprint and electorate are grounded. Do not use Plan to compensate for weak Reach assumptions. Do not use Scenarios to hide unstable base setup.",
      mathBehindIt: "No math changes. This is usage-order doctrine over existing architecture.",
      whatGoodLooksLike: "Module order is intentional, source notes are complete, and each downstream surface can be traced back to coherent upstream setup.",
      warningSigns: "Assumptions tuned before data grounding, targeting run on partial geography, or war-room recommendations generated before base coherence checks.",
      adjustmentRules: "When upstream quality is weak, pause downstream interpretation and repair sequence integrity first.",
      origins: "Authored workflow guide pack including new-race setup, turf day, weekly check-in, and end-of-cycle audit flows.",
      modelPhilosophy: "Order matters: grounded setup beats fast but unstable analysis.",
    }),
    relatedModules: Object.freeze([
      "dataOperationsGuide",
      "districtRaceContext",
      "districtTargetConfig",
      "reachOperationsGuide",
      "turnoutOperationsGuide",
      "outcomeOperationsGuide",
      "planOperationsGuide",
      "scenarioOperationsGuide",
      "warRoomOperationsGuide",
      "organizerOperationsWorkflow",
    ]),
    relatedTerms: Object.freeze(["readiness", "confidenceBand", "signal", "materialChange"]),
  }),
  operationsWorkforce: Object.freeze({
    id: "operationsWorkforce",
    title: "Operations Workforce",
    summary: "Model real staffing capacity using role-typed workforce assumptions.",
    sections: Object.freeze({
      whatItIs: "The canonical staffing and productivity layer for execution capacity.",
      whenToUse: "Use when planning organizer coverage, volunteer shifts, and paid canvassing throughput.",
      whenNotToUse: "Do not represent event impact as fake output injections.",
      feedsInto: "Feeds optimizer, turnoutContactSaturation, realism, and war room recommendations.",
      parametersExplained: "Role type, expected hours, and productivity assumptions determine capacity.",
      rangesExplained: "Role productivity varies by training, geography, and program maturity.",
      howToThink: "Capacity first, then convert to attempts and conversations through canonical rates.",
      mathBehindIt: "Workforce assumptions produce canonical capacity constraints and projections.",
      whatGoodLooksLike: "Capacity assumptions align with observed pace and staffing logs.",
      warningSigns: "Volunteer counts increase while practical coverage or quality does not.",
      adjustmentRules: "Adjust role mix before inflating per-person productivity assumptions.",
      origins: "Field operations capacity planning and execution audit needs.",
      modelPhilosophy: "Capacity changes truth constraints; it does not rewrite output truth directly.",
    }),
    relatedModules: Object.freeze(["turnoutContactSaturation", "optimizer", "warRoomDecisionSession"]),
    relatedModels: Object.freeze(["volunteerProduction", "currentFieldEfficiencyScore", "votePathOptimization"]),
    relatedTerms: Object.freeze(["field organizer", "volunteer", "paid canvasser", "capacity", "signal"]),
  }),
  budgetChannelCost: Object.freeze({
    id: "budgetChannelCost",
    title: "Budget Channel Cost",
    summary: "Maintain realistic channel cost assumptions for credible optimization and reporting.",
    sections: Object.freeze({
      whatItIs: "Canonical channel cost input layer consumed by optimizer and reports.",
      whenToUse: "Use when setting channel budgets and checking unit economics.",
      whenNotToUse: "Do not bypass with hidden per-surface cost shortcuts.",
      feedsInto: "Feeds optimizer, realism diagnostics, war room, and client/internal reports.",
      parametersExplained: "Cost per attempt/contact by channel and optional overhead controls.",
      rangesExplained: "Bands should reflect market and campaign operating conditions.",
      howToThink: "Cost assumptions are strategic constraints, not cosmetic metadata.",
      mathBehindIt: "Costs divide canonical expected impact outputs to produce efficiency views.",
      whatGoodLooksLike: "Unit economics remain plausible under stress and scenario comparison.",
      warningSigns: "Low-cost assumptions drive strategy without supporting operational evidence.",
      adjustmentRules: "Revise costs with source notes and effective date context.",
      origins: "Campaign budgeting discipline and accountable recommendation logic.",
      modelPhilosophy: "No fantasy costs in production strategy.",
    }),
    relatedModules: Object.freeze(["optimizer", "forecastOutcome", "turnoutContactSaturation"]),
    relatedModels: Object.freeze(["persuasionCost", "expectedVoteGain"]),
    relatedTerms: Object.freeze(["cost per contact", "realism", "bias", "confidence"]),
  }),
  turnoutContactSaturation: Object.freeze({
    id: "turnoutContactSaturation",
    title: "Turnout Contact Saturation",
    summary: "Track diminishing returns and contact pressure to prevent overcounted impact.",
    sections: Object.freeze({
      whatItIs: "The canonical layer for contact conversion assumptions and saturation pressure.",
      whenToUse: "Use when setting turnout lift, contact rates, and repeated-touch expectations.",
      whenNotToUse: "Do not assume linear gains at high contact frequency.",
      feedsInto: "Feeds optimizer, forecastOutcome, realism, and targeting assumptions.",
      parametersExplained: "Turnout reliability, contact probability, and diminishing mechanics.",
      rangesExplained: "Late-cycle repeated contact often has flattening marginal impact.",
      howToThink: "More touches do not imply proportional additional votes.",
      mathBehindIt: "Canonical turnout and conversion equations with saturation-aware interpretation.",
      whatGoodLooksLike: "Incremental gains taper as saturation increases.",
      warningSigns: "Projected gains remain linear despite heavy repeat contact.",
      adjustmentRules: "Reduce assumed lift before increasing volume claims.",
      origins: "Field contact effect and turnout-lift modeling discipline.",
      modelPhilosophy: "Protect strategy from over-optimistic repeated-contact assumptions.",
    }),
    relatedModules: Object.freeze(["optimizer", "targetingLab", "forecastOutcome"]),
    relatedModels: Object.freeze(["contactSaturation", "persuasionCurve", "expectedVoteGain"]),
    relatedTerms: Object.freeze(["saturation", "turnout opportunity", "contact probability", "lift"]),
  }),
  scenarioManager: Object.freeze({
    id: "scenarioManager",
    title: "Scenario Manager",
    summary: "Manage alternate assumption branches without cross-contaminating canonical state.",
    sections: Object.freeze({
      whatItIs: "A branch-control workspace for compare/load/save workflow.",
      whenToUse: "Use for alternatives, stress paths, and decision-option framing.",
      whenNotToUse: "Do not overwrite baseline without preserving rationale.",
      feedsInto: "Feeds war room, decision log, reporting comparisons, and learning audit.",
      parametersExplained: "Scenario names, active selection, and baseline comparison metadata.",
      rangesExplained: "Scenario differences should map to explicit assumption or policy deltas.",
      howToThink: "Scenario work is controlled experimentation, not ad hoc copying.",
      mathBehindIt: "No duplicate formulas; scenarios re-run canonical compute path.",
      whatGoodLooksLike: "Scenario deltas are explainable and materially decision-relevant.",
      warningSigns: "Scenario outputs diverge with undocumented input differences.",
      adjustmentRules: "Require note/evidence for critical assumption changes.",
      origins: "Decision discipline and auditable alternatives.",
      modelPhilosophy: "Branch cleanly; compare honestly.",
    }),
    relatedModules: Object.freeze(["forecastOutcome", "learningAudit", "warRoomDecisionSession"]),
    relatedModels: Object.freeze(["masterTargetingEquation", "expectedVoteGain"]),
    relatedTerms: Object.freeze(["scenario drift", "signal", "noise", "confidence"]),
  }),
  learningAudit: Object.freeze({
    id: "learningAudit",
    title: "Learning Audit",
    summary: "Capture observed results and feedback loops to calibrate future assumptions.",
    sections: Object.freeze({
      whatItIs: "A canonical learning loop for observed-vs-assumed gap tracking.",
      whenToUse: "Use after field reporting updates, major milestones, and post-election closeout.",
      whenNotToUse: "Do not auto-overwrite assumptions without governance traceability.",
      feedsInto: "Feeds governanceConfidence, templateArchetype calibration, and war room framing.",
      parametersExplained: "Observed metrics, drift recommendations, and applied recommendation log.",
      rangesExplained: "Observed variance should narrow assumptions over time when evidence improves.",
      howToThink: "Learning should reduce repeated error, not justify retrospective narratives.",
      mathBehindIt: "Compares canonical observed metrics to expected path metadata.",
      whatGoodLooksLike: "Assumption updates follow observed drift with documented rationale.",
      warningSigns: "Drift repeats while assumptions remain unchanged.",
      adjustmentRules: "Apply recommendations with note/evidence when critical.",
      origins: "Continuous improvement and campaign model accountability.",
      modelPhilosophy: "Observed beats assumed when evidence is credible.",
    }),
    relatedModules: Object.freeze(["governanceConfidence", "scenarioManager", "forecastOutcome"]),
    relatedModels: Object.freeze(["turnoutElasticity", "networkDiffusion"]),
    relatedTerms: Object.freeze(["calibration", "bias", "signal", "noise"]),
  }),
  targetUniverseMatrix: Object.freeze({
    id: "targetUniverseMatrix",
    title: "Target Universe Matrix",
    summary: "Segment the electorate into operational universes used by targeting and execution.",
    sections: Object.freeze({
      whatItIs: "Canonical segmentation layer for persuasion, turnout, base, and de-prioritized universes.",
      whenToUse: "Use when defining who is in or out of near-term field focus.",
      whenNotToUse: "Do not substitute static labels for updated empirical signals.",
      feedsInto: "Feeds targetingLab, operationsWorkforce planning, and reporting summaries.",
      parametersExplained: "Support and turnout dimensions determine matrix bucket assignment.",
      rangesExplained: "Segment shares should remain realistic for district context and data quality.",
      howToThink: "Universe definition is strategic scope control, not just data description.",
      mathBehindIt: "Derived from canonical support and turnout segmentation inputs.",
      whatGoodLooksLike: "Buckets map to actionable field strategies and realistic capacity.",
      warningSigns: "Matrix assigns broad universes with no operational throughput path.",
      adjustmentRules: "Narrow universes when capacity or confidence constraints tighten.",
      origins: "Voter segmentation and field targeting operations practice.",
      modelPhilosophy: "Clear segment boundaries reduce strategic drift.",
    }),
    relatedModules: Object.freeze(["targetingLab", "operationsWorkforce", "forecastOutcome"]),
    relatedModels: Object.freeze(["supportTurnoutMatrix", "congressionalTargetScore", "masterTargetingEquation"]),
    relatedTerms: Object.freeze(["persuasion", "turnout opportunity", "super voters", "low-propensity voters"]),
  }),
  warRoomDecisionSession: Object.freeze({
    id: "warRoomDecisionSession",
    title: "War Room Decision Session",
    summary: "Translate live conditions, forecast posture, and confidence into a clear recommendation about whether the campaign should hold, press, protect, or recalibrate.",
    sections: Object.freeze({
      whatItIs: "This is the campaign's decision-forcing layer. It takes what the system is seeing and pushes the team toward a plain-language operating call. The purpose is not to make discussions louder. It is to make them cleaner: what changed, what matters, what can be trusted, and what the campaign should actually do next.",
      whenToUse: "Use during weekly war room reviews, surge decisions, budget-pressure moments, adverse shifts, scenario comparisons, and whenever leadership needs to choose between staying the course, pressing an advantage, or tightening up against downside.",
      whenNotToUse: "Do not use it to rationalize decisions that were already politically chosen. Do not backfill a preferred story with whichever percentile or metric looks nicest. This layer is only useful if it is allowed to tell the truth about risk, fragility, and timing.",
      feedsInto: "Feeds action recommendations, decision log, and reporting narratives.",
      parametersExplained: "Decision posture depends on signal strength, forecast shape, governance confidence, readiness, pace, and whether the observed movement is broad-based or concentrated in a fragile part of the distribution.",
      rangesExplained: "Actionability depends on both magnitude and trust. A big movement in a weak-confidence environment may deserve caution. A smaller movement in a high-discipline, high-trust environment may justify action sooner. Flashy movement is not automatically decision-relevant movement.",
      howToThink: "Separate observation, interpretation, and commitment. First ask what changed. Then ask whether it is signal or noise. Then ask whether the change is strong enough, trusted enough, and important enough to justify action now. This is how the campaign avoids turning volatility into theater.",
      mathBehindIt: "Consumes canonical outputs from forecast, optimizer, governance, and events.",
      whatGoodLooksLike: "The team can state in plain language whether it is planning off the floor, the middle, or the upside. Recommendations are framed as safe, balanced, or aggressive. The discussion focuses on what is decision-worthy, not just what is visually dramatic.",
      warningSigns: "Strategy pivots triggered by noise. Leadership anchoring on the best-looking case. Teams discussing upside as if it were the baseline. Escalation without naming what confidence level the decision is actually resting on.",
      adjustmentRules: "If the evidence is noisy, narrow the claim before widening the action. If the floor is weakening, protect the downside before celebrating the headline. If the middle is strengthening with credible support, increase commitment in proportion to that stronger base rather than in proportion to the loudest upside story.",
      origins: "Campaign operations command discipline.",
      modelPhilosophy: "A good decision session does not eliminate judgment. It improves judgment by forcing the team to name what is real, what is fragile, and what kind of bet they are actually making.",
    }),
    relatedModules: Object.freeze(["forecastOutcome", "optimizer", "governanceConfidence", "scenarioManager"]),
    relatedModels: Object.freeze(["currentFieldEfficiencyScore", "expectedVoteGain", "masterTargetingEquation"]),
    relatedTerms: Object.freeze(["signal", "noise", "material change", "actionability", "median", "planningFloor", "upsideCase", "confidenceBand"]),
  }),
  campaignDataRequirements: Object.freeze({
    id: "campaignDataRequirements",
    title: "Campaign Data Requirements",
    summary: "Define the reporting discipline, source ownership, and update cadence required for the system to stay credible, current, and decision-useful.",
    sections: Object.freeze({
      whatItIs: "This is the discipline layer behind the intelligence layer. It explains what the system needs in order to keep its outputs grounded in reality. If the campaign wants the rail to feel sharp, useful, and trustworthy, this is where that trust is actually earned.",
      whenToUse: "Use during setup, ownership planning, reporting audits, handoffs between teams, and any time the campaign needs to understand whether an output is strong because reality improved or just because the inputs drifted out of accountability.",
      whenNotToUse: "Do not treat requirements as optional documentation. If an input has no owner, no source, and no cadence, it is not operationally real. It should not be allowed to quietly shape major decisions.",
      feedsInto: "Feeds governanceConfidence, forecastOutcome, learningAudit, reporting integrity, and long-run system trust.",
      parametersExplained: "The usefulness of model outputs depends on source quality, refresh cadence, owner clarity, and whether required inputs are complete, current, and auditable. Better structure narrows uncertainty. Poor discipline widens it.",
      rangesExplained: "Cadence discipline narrows uncertainty over time. Ranges only become more informative over time if the campaign is disciplined about refreshes. Daily execution updates, weekly review of assumptions, scenario refresh on material change, and post-election audit all help the system separate real movement from stale assumptions. Without cadence discipline, uncertainty stays wider than it should.",
      howToThink: "If an input has no owner, source path, or cadence, it is not operationally real. If a number cannot be traced back to a believable source path, it should not be given strong narrative weight. The right question is not just whether the model produced an answer. The right question is whether the campaign earned the right to trust that answer today.",
      mathBehindIt: "This layer does not create the campaign's outcome on its own. It governs the quality of the evidence feeding the canonical system so that modeled outputs remain interpretable and durable.",
      whatGoodLooksLike: "Every important number has a source, an owner, a cadence, and a reason it matters. The campaign knows who updates what, when it gets reviewed, and what downstream module it affects. That is how intelligence stops feeling decorative and starts feeling operational.",
      warningSigns: "Stale inputs quietly surviving across multiple reviews. Ambiguous ownership. Numbers that move with no clear source path. Teams explaining model outputs more confidently than they can explain the reporting discipline underneath them.",
      adjustmentRules: "When ownership is weak or freshness slips, reduce confidence language before you reduce honesty. Reassign owners, restore cadence, and close provenance gaps before treating the latest model view as fully decision-ready.",
      origins: "Operating discipline contract for campaign collaboration.",
      modelPhilosophy: "The smartest-looking system in the world becomes underwhelming if its inputs drift out of ownership. Intelligence becomes durable when the campaign treats data discipline as part of strategy, not as back-office cleanup.",
    }),
    relatedModules: Object.freeze(["scenarioManager", "learningAudit", "governanceConfidence"]),
    relatedTerms: Object.freeze(["confidence", "confidenceBand", "calibration", "signal", "readiness"]),
  }),
  durabilityTrustStandards: Object.freeze({
    id: "durabilityTrustStandards",
    title: "Durability & Trust Standards",
    summary: "System integrity doctrine for provenance, snapshots, traceability, and honest unknown states.",
    sections: Object.freeze({
      whatItIs: "A first-class trust standard page for long-run system explainability.",
      whenToUse: "Use for release readiness, audit prep, and high-stakes decision reviews.",
      whenNotToUse: "Do not collapse trust checks into cosmetic status labels.",
      feedsInto: "Feeds governanceConfidence, reporting trust summaries, and audit posture.",
      parametersExplained: "Standards include: provenance on major numbers; snapshot discipline; entered vs derived vs learned value clarity; honest unknown states; default-to-observed handoff; override logging with rationale; change transparency; trust summaries on major pages; no shadow logic; reproducibility; version awareness; decision traceability.",
      rangesExplained: "Trust confidence degrades as provenance coverage drops, snapshot gaps grow, overrides lose rationale, and reproducibility diverges across sessions/exports.",
      howToThink: "Durability is behavior over time: every critical change should be explainable, attributable, and reproducible.",
      mathBehindIt: "No new model math; standards constrain whether canonical outputs can be trusted for decisions.",
      whatGoodLooksLike: "Major numbers are traceable to canonical inputs, snapshot history explains changes, and reports/exports match runtime canonical outputs.",
      warningSigns: "Silent overrides, hidden mutation paths, version ambiguity, unknown-state suppression, and report/runtime mismatch.",
      adjustmentRules: "Block high-significance actions when trust standards fail; require rationale and lineage before restoring full-confidence status.",
      origins: "Operational integrity and decision accountability practice.",
      modelPhilosophy: "Trustworthy systems reveal uncertainty and lineage, not just outcomes.",
    }),
    relatedModules: Object.freeze(["governanceConfidence", "warRoomDecisionSession", "learningAudit"]),
    relatedTerms: Object.freeze(["confidence", "bias", "signal", "noise"]),
  }),
});

/**
 * @param {string=} moduleId
 */
export function getDoctrineModule(moduleId = ""){
  const id = String(moduleId || "").trim();
  if (!id) return null;
  return MODULE_DOCTRINE_REGISTRY[id] || null;
}

export function listDoctrineModules(){
  return Object.values(MODULE_DOCTRINE_REGISTRY);
}
