// @ts-check

/**
 * Canonical doctrine registry.
 * This file stores static meaning only (no live values, no compute logic).
 */
export const MODULE_DOCTRINE_REGISTRY = Object.freeze({
  targetingLab: Object.freeze({
    id: "targetingLab",
    title: "Targeting Lab",
    summary: "Rank geographies and targets with canonical targeting outputs before execution planning.",
    sections: Object.freeze({
      whatItIs: "A prioritization workspace that converts canonical model outputs into ranked field targets.",
      whenToUse: "Use when defining who to contact first, where to deploy organizers, and where to allocate limited attempts.",
      whenNotToUse: "Do not use as a replacement for validation, readiness, or realism checks.",
      feedsInto: "Feeds targetUniverseMatrix, optimizer, forecastOutcome, and warRoomDecisionSession.",
      parametersExplained: "Weights shape emphasis; they do not create a second math engine.",
      rangesExplained: "Weight ranges are relative priorities, not absolute probabilities.",
      howToThink: "Rank by expected strategic value per constrained unit of field capacity.",
      mathBehindIt: "Master targeting law v1: persuasionMultiplier=max(0,1-2*abs(0.5-supportScore)); adjustedPersuasion=persuasionIndex*persuasionMultiplier; baseScore=(voteWeight*votePotential)+(turnoutWeight*turnoutOpportunity)+(persuasionWeight*adjustedPersuasion)+(fieldWeight*fieldEfficiency)+(networkWeight*networkValue); targetScore=baseScore*contactProbability*geographicMultiplier*saturationMultiplier; expectedNetVoteValue=targetScore*expectedVotesReachable/costPerContact.",
      whatGoodLooksLike: "Top-ranked targets remain stable under modest assumption perturbations.",
      warningSigns: "Large ranking swings from tiny input edits indicate unstable assumptions.",
      adjustmentRules: "Adjust weighting only when doctrine-backed strategic objective changes.",
      origins: "Built from canonical targeting law and practical field prioritization constraints.",
      modelPhilosophy: "One architecture, many strategic emphases.",
    }),
    relatedModules: Object.freeze(["targetUniverseMatrix", "optimizer", "forecastOutcome"]),
    relatedModels: Object.freeze([
      "supportTurnoutMatrix",
      "congressionalTargetScore",
      "masterTargetingEquation",
      "expectedVoteGain",
      "contactSaturation",
      "geographicPersuasionClustering",
    ]),
    relatedTerms: Object.freeze(["variance", "lift", "contact probability", "saturation", "vote path"]),
  }),
  optimizer: Object.freeze({
    id: "optimizer",
    title: "Optimizer",
    summary: "Allocate finite budget and capacity across channels without violating canonical constraints.",
    sections: Object.freeze({
      whatItIs: "A constrained allocation layer consuming canonical conversion and cost outputs.",
      whenToUse: "Use when choosing between doors, calls, texts, mail, and lit drop tradeoffs.",
      whenNotToUse: "Do not use when readiness or validation blockers remain unresolved.",
      feedsInto: "Feeds forecastOutcome, budgetChannelCost, and warRoomDecisionSession.",
      parametersExplained: "Objective and constraints control tradeoffs, not formula architecture.",
      rangesExplained: "Channel costs and throughput bounds represent operational feasibility bands.",
      howToThink: "Maximize expected strategic value per constrained dollar and organizer hour.",
      mathBehindIt: "Uses canonical expected net vote value, capacity, and channel cost inputs.",
      whatGoodLooksLike: "Allocation reflects both cost efficiency and execution realism.",
      warningSigns: "Over-concentration in one low-cost channel with weak conversion confidence.",
      adjustmentRules: "Revise constraints and assumptions before forcing objective-only changes.",
      origins: "Resource optimization under campaign execution constraints.",
      modelPhilosophy: "Transparent constraint tradeoff, no hidden overrides.",
    }),
    relatedModules: Object.freeze(["budgetChannelCost", "turnoutContactSaturation", "forecastOutcome"]),
    relatedModels: Object.freeze(["votePathOptimization", "persuasionCost", "expectedVoteGain", "masterTargetingEquation"]),
    relatedTerms: Object.freeze(["cost per contact", "contact probability", "realism", "confidence"]),
  }),
  forecastOutcome: Object.freeze({
    id: "forecastOutcome",
    title: "Forecast Outcome",
    summary: "Translate current assumptions and execution plan into confidence-aware outcome framing.",
    sections: Object.freeze({
      whatItIs: "The canonical forecast layer for projected vote path, outcome posture, and uncertainty framing. This is where the system stops pretending there is one magic number and shows the range of what is realistically in play.",
      whenToUse: "Use for checkpoint reviews, scenario comparisons, leadership conversations, and pacing decisions that require both headline direction and risk shape.",
      whenNotToUse: "Do not present forecast outputs as guarantees. Do not let top-end outcomes substitute for readiness, realism, or evidence review.",
      feedsInto: "Feeds governanceConfidence, warRoomDecisionSession, scenario framing, and reporting narratives.",
      parametersExplained: "Forecast sensitivity reflects the interaction of assumptions, execution pace, uncertainty, and evidence quality.",
      rangesExplained: "Outcome bands represent modeled uncertainty, not promises. In the live rail, percentiles shown are P10, P50, and P90. They are points on one distribution: P10 is a cautious lower-tail case, P50 is the middle case, and P90 is a strong upside edge. If additional cuts like P30 or P70 are exposed later, read them as intermediate confidence points between floor and ceiling.",
      howToThink: "Treat forecast as conditional truth, not absolute truth. Ask what the honest middle is, what downside is survivable, and how much of the plan depends on upside.",
      mathBehindIt: "Builds from canonical expected values plus uncertainty framing layers. Percentiles summarize plausible spread around the modeled center to distinguish stable, fragile, and high-variance paths.",
      whatGoodLooksLike: "A strong forecast has a believable middle, manageable downside, and movement traceable to real changes in assumptions, evidence, or execution.",
      warningSigns: "Large confidence jumps without corresponding data or assumption changes; dependence on top-end outcomes to hit goal; widening ranges without explanation; favorable headlines paired with weak readiness.",
      adjustmentRules: "Recalibrate assumptions before escalating narrative confidence. If only upside supports the plan, state that directly. If lower-end outcomes are intolerable, revise scope, pacing, or exposure.",
      origins: "Decision-support forecasting, not decorative charting.",
      modelPhilosophy: "Honest uncertainty over false precision. The point is not impressive numbers; it is choosing the right confidence level for the decision in front of the team.",
    }),
    relatedModules: Object.freeze(["governanceConfidence", "learningAudit", "warRoomDecisionSession"]),
    relatedModels: Object.freeze(["expectedVoteGain", "turnoutElasticity", "masterTargetingEquation"]),
    relatedTerms: Object.freeze(["confidence", "confidenceBand", "percentileRange", "median", "planningFloor", "upsideCase", "variance", "signal", "noise", "scenario drift"]),
  }),
  governanceConfidence: Object.freeze({
    id: "governanceConfidence",
    title: "Governance Confidence",
    summary: "Score whether the model should be trusted given evidence, coverage, and integrity checks.",
    sections: Object.freeze({
      whatItIs: "A trust framing layer separating input quality from model mechanics.",
      whenToUse: "Use before decisions, exports, and client-facing reporting.",
      whenNotToUse: "Do not use as a substitute for fixing missing required inputs.",
      feedsInto: "Feeds readiness, war room framing, and reporting trust language.",
      parametersExplained: "Confidence combines data quality, execution signal, and evidence coverage.",
      rangesExplained: "Low confidence does not automatically mean the model is broken. It means the team should commit more cautiously and separate what is known, inferred, and weakly evidenced.",
      howToThink: "A clean output is not the same as a trustworthy output. Confidence comes from evidence quality, update discipline, provenance, and operational realism.",
      mathBehindIt: "Computed from canonical governance and validation aggregates.",
      whatGoodLooksLike: "Confidence shifts are explainable. Evidence improvements increase confidence; stale required inputs lower it. Movement should always have named causes.",
      warningSigns: "Confidence rising while required inputs are missing, confidence language stronger than evidence, or polished output used as a substitute for reporting discipline.",
      adjustmentRules: "Require provenance updates before overriding confidence flags.",
      origins: "Operational trust governance in campaign analytics workflows.",
      modelPhilosophy: "Trust is earned, not implied by output format.",
    }),
    relatedModules: Object.freeze(["learningAudit", "scenarioManager", "forecastOutcome"]),
    relatedTerms: Object.freeze(["confidence", "confidenceBand", "percentileRange", "bias", "calibration", "signal", "noise"]),
  }),
  templateArchetype: Object.freeze({
    id: "templateArchetype",
    title: "Template Archetype",
    summary: "Set initial planning archetype by race context while preserving canonical engine architecture.",
    sections: Object.freeze({
      whatItIs: "A default profile system for initial assumptions and ranges.",
      whenToUse: "Use at campaign setup and when opening new scenario branches.",
      whenNotToUse: "Do not treat templates as final assumptions for late-cycle decisions.",
      feedsInto: "Feeds targetingLab, forecastOutcome, turnoutContactSaturation, and optimizer.",
      parametersExplained: "Template dimensions set default assumptions profile and benchmark scope.",
      rangesExplained: "Template ranges are starting priors; observed data should override over time.",
      howToThink: "Template first, then calibrate with campaign-specific evidence.",
      mathBehindIt: "No independent math; configures canonical model input defaults.",
      whatGoodLooksLike: "Template assumptions converge toward observed campaign behavior.",
      warningSigns: "Template defaults remain untouched despite contradictory field evidence.",
      adjustmentRules: "Document template overrides with rationale in governance notes.",
      origins: "Operational startup discipline for campaign modeling.",
      modelPhilosophy: "Faster setup without sacrificing explicit assumptions.",
    }),
    relatedModules: Object.freeze(["governanceConfidence", "scenarioManager", "learningAudit"]),
    relatedModels: Object.freeze(["turnoutElasticity"]),
    relatedTerms: Object.freeze(["calibration", "bias", "readiness"]),
  }),
  operationsWorkforce: Object.freeze({
    id: "operationsWorkforce",
    title: "Operations Workforce",
    summary: "Model real staffing capacity using role-typed workforce assumptions.",
    sections: Object.freeze({
      whatItIs: "The canonical staffing and productivity layer for execution capacity.",
      whenToUse: "Use when planning organizer coverage, volunteer shifts, and paid canvassing throughput.",
      whenNotToUse: "Do not represent event impact as fake output injections.",
      feedsInto: "Feeds optimizer, turnoutContactSaturation, realism, and war room recommendations.",
      parametersExplained: "Role type, expected hours, and productivity assumptions determine capacity.",
      rangesExplained: "Role productivity varies by training, geography, and program maturity.",
      howToThink: "Capacity first, then convert to attempts and conversations through canonical rates.",
      mathBehindIt: "Workforce assumptions produce canonical capacity constraints and projections.",
      whatGoodLooksLike: "Capacity assumptions align with observed pace and staffing logs.",
      warningSigns: "Volunteer counts increase while practical coverage or quality does not.",
      adjustmentRules: "Adjust role mix before inflating per-person productivity assumptions.",
      origins: "Field operations capacity planning and execution audit needs.",
      modelPhilosophy: "Capacity changes truth constraints; it does not rewrite output truth directly.",
    }),
    relatedModules: Object.freeze(["turnoutContactSaturation", "optimizer", "warRoomDecisionSession"]),
    relatedModels: Object.freeze(["volunteerProduction", "currentFieldEfficiencyScore", "votePathOptimization"]),
    relatedTerms: Object.freeze(["field organizer", "volunteer", "paid canvasser", "capacity", "signal"]),
  }),
  budgetChannelCost: Object.freeze({
    id: "budgetChannelCost",
    title: "Budget Channel Cost",
    summary: "Maintain realistic channel cost assumptions for credible optimization and reporting.",
    sections: Object.freeze({
      whatItIs: "Canonical channel cost input layer consumed by optimizer and reports.",
      whenToUse: "Use when setting channel budgets and checking unit economics.",
      whenNotToUse: "Do not bypass with hidden per-surface cost shortcuts.",
      feedsInto: "Feeds optimizer, realism diagnostics, war room, and client/internal reports.",
      parametersExplained: "Cost per attempt/contact by channel and optional overhead controls.",
      rangesExplained: "Bands should reflect market and campaign operating conditions.",
      howToThink: "Cost assumptions are strategic constraints, not cosmetic metadata.",
      mathBehindIt: "Costs divide canonical expected impact outputs to produce efficiency views.",
      whatGoodLooksLike: "Unit economics remain plausible under stress and scenario comparison.",
      warningSigns: "Low-cost assumptions drive strategy without supporting operational evidence.",
      adjustmentRules: "Revise costs with source notes and effective date context.",
      origins: "Campaign budgeting discipline and accountable recommendation logic.",
      modelPhilosophy: "No fantasy costs in production strategy.",
    }),
    relatedModules: Object.freeze(["optimizer", "forecastOutcome", "turnoutContactSaturation"]),
    relatedModels: Object.freeze(["persuasionCost", "expectedVoteGain"]),
    relatedTerms: Object.freeze(["cost per contact", "realism", "bias", "confidence"]),
  }),
  turnoutContactSaturation: Object.freeze({
    id: "turnoutContactSaturation",
    title: "Turnout Contact Saturation",
    summary: "Track diminishing returns and contact pressure to prevent overcounted impact.",
    sections: Object.freeze({
      whatItIs: "The canonical layer for contact conversion assumptions and saturation pressure.",
      whenToUse: "Use when setting turnout lift, contact rates, and repeated-touch expectations.",
      whenNotToUse: "Do not assume linear gains at high contact frequency.",
      feedsInto: "Feeds optimizer, forecastOutcome, realism, and targeting assumptions.",
      parametersExplained: "Turnout reliability, contact probability, and diminishing mechanics.",
      rangesExplained: "Late-cycle repeated contact often has flattening marginal impact.",
      howToThink: "More touches do not imply proportional additional votes.",
      mathBehindIt: "Canonical turnout and conversion equations with saturation-aware interpretation.",
      whatGoodLooksLike: "Incremental gains taper as saturation increases.",
      warningSigns: "Projected gains remain linear despite heavy repeat contact.",
      adjustmentRules: "Reduce assumed lift before increasing volume claims.",
      origins: "Field contact effect and turnout-lift modeling discipline.",
      modelPhilosophy: "Protect strategy from over-optimistic repeated-contact assumptions.",
    }),
    relatedModules: Object.freeze(["optimizer", "targetingLab", "forecastOutcome"]),
    relatedModels: Object.freeze(["contactSaturation", "persuasionCurve", "expectedVoteGain"]),
    relatedTerms: Object.freeze(["saturation", "turnout opportunity", "contact probability", "lift"]),
  }),
  scenarioManager: Object.freeze({
    id: "scenarioManager",
    title: "Scenario Manager",
    summary: "Manage alternate assumption branches without cross-contaminating canonical state.",
    sections: Object.freeze({
      whatItIs: "A branch-control workspace for compare/load/save workflow.",
      whenToUse: "Use for alternatives, stress paths, and decision-option framing.",
      whenNotToUse: "Do not overwrite baseline without preserving rationale.",
      feedsInto: "Feeds war room, decision log, reporting comparisons, and learning audit.",
      parametersExplained: "Scenario names, active selection, and baseline comparison metadata.",
      rangesExplained: "Scenario differences should map to explicit assumption or policy deltas.",
      howToThink: "Scenario work is controlled experimentation, not ad hoc copying.",
      mathBehindIt: "No duplicate formulas; scenarios re-run canonical compute path.",
      whatGoodLooksLike: "Scenario deltas are explainable and materially decision-relevant.",
      warningSigns: "Scenario outputs diverge with undocumented input differences.",
      adjustmentRules: "Require note/evidence for critical assumption changes.",
      origins: "Decision discipline and auditable alternatives.",
      modelPhilosophy: "Branch cleanly; compare honestly.",
    }),
    relatedModules: Object.freeze(["forecastOutcome", "learningAudit", "warRoomDecisionSession"]),
    relatedModels: Object.freeze(["masterTargetingEquation", "expectedVoteGain"]),
    relatedTerms: Object.freeze(["scenario drift", "signal", "noise", "confidence"]),
  }),
  learningAudit: Object.freeze({
    id: "learningAudit",
    title: "Learning Audit",
    summary: "Capture observed results and feedback loops to calibrate future assumptions.",
    sections: Object.freeze({
      whatItIs: "A canonical learning loop for observed-vs-assumed gap tracking.",
      whenToUse: "Use after field reporting updates, major milestones, and post-election closeout.",
      whenNotToUse: "Do not auto-overwrite assumptions without governance traceability.",
      feedsInto: "Feeds governanceConfidence, templateArchetype calibration, and war room framing.",
      parametersExplained: "Observed metrics, drift recommendations, and applied recommendation log.",
      rangesExplained: "Observed variance should narrow assumptions over time when evidence improves.",
      howToThink: "Learning should reduce repeated error, not justify retrospective narratives.",
      mathBehindIt: "Compares canonical observed metrics to expected path metadata.",
      whatGoodLooksLike: "Assumption updates follow observed drift with documented rationale.",
      warningSigns: "Drift repeats while assumptions remain unchanged.",
      adjustmentRules: "Apply recommendations with note/evidence when critical.",
      origins: "Continuous improvement and campaign model accountability.",
      modelPhilosophy: "Observed beats assumed when evidence is credible.",
    }),
    relatedModules: Object.freeze(["governanceConfidence", "scenarioManager", "forecastOutcome"]),
    relatedModels: Object.freeze(["turnoutElasticity", "networkDiffusion"]),
    relatedTerms: Object.freeze(["calibration", "bias", "signal", "noise"]),
  }),
  targetUniverseMatrix: Object.freeze({
    id: "targetUniverseMatrix",
    title: "Target Universe Matrix",
    summary: "Segment the electorate into operational universes used by targeting and execution.",
    sections: Object.freeze({
      whatItIs: "Canonical segmentation layer for persuasion, turnout, base, and de-prioritized universes.",
      whenToUse: "Use when defining who is in or out of near-term field focus.",
      whenNotToUse: "Do not substitute static labels for updated empirical signals.",
      feedsInto: "Feeds targetingLab, operationsWorkforce planning, and reporting summaries.",
      parametersExplained: "Support and turnout dimensions determine matrix bucket assignment.",
      rangesExplained: "Segment shares should remain realistic for district context and data quality.",
      howToThink: "Universe definition is strategic scope control, not just data description.",
      mathBehindIt: "Derived from canonical support and turnout segmentation inputs.",
      whatGoodLooksLike: "Buckets map to actionable field strategies and realistic capacity.",
      warningSigns: "Matrix assigns broad universes with no operational throughput path.",
      adjustmentRules: "Narrow universes when capacity or confidence constraints tighten.",
      origins: "Voter segmentation and field targeting operations practice.",
      modelPhilosophy: "Clear segment boundaries reduce strategic drift.",
    }),
    relatedModules: Object.freeze(["targetingLab", "operationsWorkforce", "forecastOutcome"]),
    relatedModels: Object.freeze(["supportTurnoutMatrix", "congressionalTargetScore", "masterTargetingEquation"]),
    relatedTerms: Object.freeze(["persuasion", "turnout opportunity", "super voters", "low-propensity voters"]),
  }),
  warRoomDecisionSession: Object.freeze({
    id: "warRoomDecisionSession",
    title: "War Room Decision Session",
    summary: "Convert new information into disciplined, confidence-aware decisions with follow-through.",
    sections: Object.freeze({
      whatItIs: "A structured decision layer for high-pressure operational reviews.",
      whenToUse: "Use at daily/weekly review checkpoints or when meaningful change appears.",
      whenNotToUse: "Do not react to noise without material signal confirmation.",
      feedsInto: "Feeds action recommendations, decision log, and reporting narratives.",
      parametersExplained: "Change classification, decision significance, owner assignment, and follow-up.",
      rangesExplained: "Actionability rises when signal is meaningful and trustworthy. Large movement in weak-confidence conditions can still require caution; smaller movement in high-trust conditions can be more decision-relevant.",
      howToThink: "Separate observation, interpretation, and commitment. Ask what changed, whether it is signal or noise, and whether confidence is strong enough to justify action now.",
      mathBehindIt: "Consumes canonical outputs from forecast, optimizer, governance, and events.",
      whatGoodLooksLike: "Teams can explain whether they are planning off the floor, the middle, or the upside. Decisions are framed plainly as safe, balanced, or aggressive.",
      warningSigns: "Strategy pivots triggered by noise, leadership anchoring on best-looking case, upside treated as baseline, or actions taken without naming confidence level.",
      adjustmentRules: "Escalate only when change is classified as strong signal/actionable shift.",
      origins: "Campaign operations command discipline.",
      modelPhilosophy: "Fast decisions, slow panic.",
    }),
    relatedModules: Object.freeze(["forecastOutcome", "optimizer", "governanceConfidence", "scenarioManager"]),
    relatedModels: Object.freeze(["currentFieldEfficiencyScore", "expectedVoteGain", "masterTargetingEquation"]),
    relatedTerms: Object.freeze(["signal", "noise", "material change", "actionability", "median", "planningFloor", "upsideCase", "confidenceBand"]),
  }),
  campaignDataRequirements: Object.freeze({
    id: "campaignDataRequirements",
    title: "Campaign Data Requirements",
    summary: "Operating contract for what campaigns must provide, where it is entered, and what it powers.",
    sections: Object.freeze({
      whatItIs: "A first-class manual page defining required campaign inputs and reporting discipline.",
      whenToUse: "Use during onboarding, recurring check-ins, and before readiness reviews.",
      whenNotToUse: "Do not treat this as optional checklist copy.",
      feedsInto: "Feeds validation, readiness, reporting, and war room trust framing.",
      parametersExplained: "Required input homes: Campaign Setup/Controls; Targeting Lab universe inputs; Operations Hub workforce; Turnout/Contact channel inputs; Budget/Channel CPA inputs; Model assumptions; Daily/weekly reporting; Learning/Audit entry; Scenario Manager; Calendar/Events; War Room ZIP/weather controls (when active).",
      rangesExplained: "Cadence discipline narrows uncertainty over time: daily execution updates, weekly assumption/status review, scenario refresh on material change, and post-election audit with observed outcomes.",
      howToThink: "If an input has no owner, source path, or cadence, it is not operationally real. When ranges look surprisingly favorable, first verify whether inputs support that story.",
      mathBehindIt: "No independent math; this page defines canonical intake discipline that gates readiness and trust.",
      whatGoodLooksLike: "Every critical required input has a known location, accountable owner, update cadence, and visible downstream module impact.",
      warningSigns: "Repeated missing fields, stale reporting cadence, missing source notes, and assumptions changed without documented rationale.",
      adjustmentRules: "Escalate blockers before decision deadlines, degrade module trust when cadence breaks, and require post-election closeout before archived learning is marked complete.",
      origins: "Operating discipline contract for campaign collaboration.",
      modelPhilosophy: "Transparent requirements prevent preventable model failure.",
    }),
    relatedModules: Object.freeze(["scenarioManager", "learningAudit", "governanceConfidence"]),
    relatedTerms: Object.freeze(["confidence", "confidenceBand", "calibration", "signal", "readiness"]),
  }),
  durabilityTrustStandards: Object.freeze({
    id: "durabilityTrustStandards",
    title: "Durability & Trust Standards",
    summary: "System integrity doctrine for provenance, snapshots, traceability, and honest unknown states.",
    sections: Object.freeze({
      whatItIs: "A first-class trust standard page for long-run system explainability.",
      whenToUse: "Use for release readiness, audit prep, and high-stakes decision reviews.",
      whenNotToUse: "Do not collapse trust checks into cosmetic status labels.",
      feedsInto: "Feeds governanceConfidence, reporting trust summaries, and audit posture.",
      parametersExplained: "Standards include: provenance on major numbers; snapshot discipline; entered vs derived vs learned value clarity; honest unknown states; default-to-observed handoff; override logging with rationale; change transparency; trust summaries on major pages; no shadow logic; reproducibility; version awareness; decision traceability.",
      rangesExplained: "Trust confidence degrades as provenance coverage drops, snapshot gaps grow, overrides lose rationale, and reproducibility diverges across sessions/exports.",
      howToThink: "Durability is behavior over time: every critical change should be explainable, attributable, and reproducible.",
      mathBehindIt: "No new model math; standards constrain whether canonical outputs can be trusted for decisions.",
      whatGoodLooksLike: "Major numbers are traceable to canonical inputs, snapshot history explains changes, and reports/exports match runtime canonical outputs.",
      warningSigns: "Silent overrides, hidden mutation paths, version ambiguity, unknown-state suppression, and report/runtime mismatch.",
      adjustmentRules: "Block high-significance actions when trust standards fail; require rationale and lineage before restoring full-confidence status.",
      origins: "Operational integrity and decision accountability practice.",
      modelPhilosophy: "Trustworthy systems reveal uncertainty and lineage, not just outcomes.",
    }),
    relatedModules: Object.freeze(["governanceConfidence", "warRoomDecisionSession", "learningAudit"]),
    relatedTerms: Object.freeze(["confidence", "bias", "signal", "noise"]),
  }),
});

/**
 * @param {string=} moduleId
 */
export function getDoctrineModule(moduleId = ""){
  const id = String(moduleId || "").trim();
  if (!id) return null;
  return MODULE_DOCTRINE_REGISTRY[id] || null;
}

export function listDoctrineModules(){
  return Object.values(MODULE_DOCTRINE_REGISTRY);
}
