// @ts-check
/** @param {import("./types").PreflightElsCtx} ctx */
export function preflightElsModule(ctx){
  const { els, recordError } = ctx || {};
  try{
    const required = [
      "scenarioName",
      "buildStamp",
      "selfTestGate",
      "persistenceStatus",
      "btnDiagnostics",
      "btnResetAll",
      "diagModal",
      "diagErrors",
      "btnDiagClose",
      "btnCopyDebug",
      "raceType",
      "electionDate",
      "weeksRemaining",
      "mode",
      "universeSize",
      "turnoutA",
      "turnoutB",
      "bandWidth",
      "btnAddCandidate",
      "yourCandidate",
      "candTbody",
      "undecidedPct",
      "undecidedMode",
      "persuasionPct",
      "earlyVoteExp",
      "censusPhase1Card",
      "censusApiKey",
      "censusAcsYear",
      "censusResolution",
      "censusMetricSet",
      "censusStateFips",
      "censusCountyFips",
      "censusPlaceFips",
      "censusContextHint",
      "btnCensusLoadGeo",
      "btnCensusFetchRows",
      "censusGeoSelect",
      "censusAggregateTbody",
      "censusAdvisoryTbody",
      "censusAdvisoryStatus",
      "censusMap",
      "censusMapStatus",
      "btnCensusLoadMap",
      "btnCensusClearMap",
      "btnCensusSetRaceFootprint",
      "btnCensusClearRaceFootprint",
      "censusApplyAdjustmentsToggle",
      "censusApplyAdjustmentsStatus",
      "targetingGeoLevel",
      "targetingModelId",
      "targetingWeightVotePotential",
      "targetingWeightTurnoutOpportunity",
      "targetingWeightPersuasionIndex",
      "targetingWeightFieldEfficiency",
      "btnTargetingResetWeights",
      "btnRunTargeting",
      "targetingStatus",
      "targetingMeta",
      "targetingResultsTbody",
    ];
    const missing = required.filter((k) => els[k] == null);
    if (missing.length) recordError("dom-preflight", `Missing required element(s): ${missing.join(", ")}`);
  } catch { /* ignore */ }
}
