// @ts-check

export const DEFAULT_GOLDEN_NOW_ISO = "2026-03-20T12:00:00.000Z";

/**
 * Representative full-state fixtures for H11 regression confidence.
 * Each fixture seeds a canonical state spanning multiple domains.
 */
export const GOLDEN_FULL_STATE_FIXTURES = [
  {
    id: "municipal_race",
    name: "Municipal race baseline",
    nowIso: DEFAULT_GOLDEN_NOW_ISO,
    statePatch: {
      revision: 101,
      domains: {
        campaign: {
          campaignId: "chi_ward_12",
          campaignName: "Ward 12 Forward",
          officeId: "alder_ward_12",
          scenarioName: "municipal_baseline",
        },
        district: {
          revision: 7,
          templateProfile: {
            raceType: "municipal",
            officeLevel: "city",
            electionType: "general",
            seatContext: "ward",
            partisanshipMode: "nonpartisan",
            salienceLevel: "medium",
          },
          form: {
            electionDate: "2027-02-23",
            weeksRemaining: "18",
            mode: "turnout",
            universeBasis: "registered",
            universeSize: 28000,
            turnoutA: 33,
            turnoutB: 47,
            bandWidth: 6,
          },
        },
        ballot: {
          yourCandidateId: "cand_luna",
          undecidedPct: 9,
          candidateRefs: {
            byId: {
              cand_luna: { id: "cand_luna", name: "Luna Ortiz", supportPct: 48 },
              cand_gray: { id: "cand_gray", name: "Evan Gray", supportPct: 43 },
            },
            order: ["cand_luna", "cand_gray"],
          },
          userSplitByCandidateId: {
            cand_luna: 56,
            cand_gray: 44,
          },
        },
        candidateHistory: {
          revision: 4,
          matchedRecordCount: 2,
          records: [
            {
              recordId: "hist_muni_2023",
              office: "Alderman Ward 12",
              cycleYear: 2023,
              electionType: "general",
              candidateName: "Luna Ortiz",
              party: "NP",
              voteShare: 50.7,
              margin: 1.4,
              turnoutContext: 31.8,
              repeatCandidate: true,
              overUnderPerformancePct: 0.8,
            },
            {
              recordId: "hist_muni_2019",
              office: "Alderman Ward 12",
              cycleYear: 2019,
              electionType: "general",
              candidateName: "Luna Ortiz",
              party: "NP",
              voteShare: 49.3,
              margin: -0.6,
              turnoutContext: 29.1,
              repeatCandidate: false,
              overUnderPerformancePct: -0.4,
            },
          ],
        },
        targeting: {
          revision: 6,
          config: {
            geoLevel: "precinct",
            modelId: "municipal_turnout_v1",
            topN: 14,
            minScore: 0.42,
            onlyRaceFootprint: true,
          },
          runtime: {
            statusText: "Municipal targeting ready.",
            lastRunAt: "2026-03-20T11:20:00.000Z",
            rows: [
              { geoid: "17031012001", score: 0.78, isTopTarget: true, reachableVoters: 540, fieldEfficiency: 0.74 },
              { geoid: "17031012002", score: 0.69, isTopTarget: true, reachableVoters: 410, fieldEfficiency: 0.7 },
              { geoid: "17031012003", score: 0.38, isTopTarget: false, reachableVoters: 180, fieldEfficiency: 0.51 },
            ],
          },
        },
        census: {
          revision: 5,
          config: {
            year: "2024",
            resolution: "tract",
            metricSet: "core",
            stateFips: "17",
            countyFips: "031",
            placeFips: "14000",
            applyAdjustedAssumptions: true,
          },
          selection: {
            selectedGeoids: ["17031012001", "17031012002"],
            loadedRowCount: 2,
          },
          runtime: {
            statusText: "Municipal census rows loaded.",
            aggregateRows: [{ key: "population", value: 12240 }],
            advisoryRows: [],
          },
        },
        outcome: {
          revision: 4,
          controls: {
            mcMode: "basic",
            mcVolatility: "med",
          },
          cache: {
            mcLastHash: "mc_municipal_01",
            mcLast: {
              winProb: 0.57,
              expectedMargin: 1.2,
              p05Margin: -1.5,
              p95Margin: 3.8,
            },
            sensitivityRows: [{ label: "Turnout reliability", impact: 0.21 }],
            surfaceRows: [{ x: 0.9, y: 1.1, winProb: 0.56 }],
            surfaceStatusText: "Municipal surface ready.",
            surfaceSummaryText: "Moderate turnout sensitivity.",
          },
        },
      },
    },
  },
  {
    id: "county_race",
    name: "County race baseline",
    nowIso: DEFAULT_GOLDEN_NOW_ISO,
    statePatch: {
      revision: 133,
      domains: {
        campaign: {
          campaignId: "dupage_board_2",
          campaignName: "County Board Momentum",
          officeId: "county_board_d2",
          scenarioName: "county_general_base",
        },
        district: {
          revision: 9,
          templateProfile: {
            raceType: "county",
            officeLevel: "county",
            electionType: "general",
            seatContext: "district",
            partisanshipMode: "competitive",
            salienceLevel: "medium",
          },
          form: {
            electionDate: "2026-11-03",
            weeksRemaining: "31",
            mode: "persuasion",
            universeBasis: "registered",
            universeSize: 96000,
            turnoutA: 41,
            turnoutB: 56,
            bandWidth: 5,
          },
        },
        ballot: {
          yourCandidateId: "cand_reyes",
          undecidedPct: 11,
          candidateRefs: {
            byId: {
              cand_reyes: { id: "cand_reyes", name: "Marisol Reyes", supportPct: 45 },
              cand_holt: { id: "cand_holt", name: "David Holt", supportPct: 44 },
            },
            order: ["cand_reyes", "cand_holt"],
          },
          userSplitByCandidateId: {
            cand_reyes: 52,
            cand_holt: 48,
          },
        },
        candidateHistory: {
          revision: 5,
          matchedRecordCount: 2,
          records: [
            {
              recordId: "hist_county_2022",
              office: "County Board District 2",
              cycleYear: 2022,
              electionType: "general",
              candidateName: "Marisol Reyes",
              party: "DEM",
              voteShare: 50.9,
              margin: 1.8,
              turnoutContext: 61.4,
              repeatCandidate: true,
              overUnderPerformancePct: 1.2,
            },
            {
              recordId: "hist_county_2018",
              office: "County Board District 2",
              cycleYear: 2018,
              electionType: "general",
              candidateName: "David Holt",
              party: "REP",
              voteShare: 49.1,
              margin: -1.8,
              turnoutContext: 57.9,
              repeatCandidate: false,
              overUnderPerformancePct: -0.9,
            },
          ],
        },
        census: {
          revision: 7,
          config: {
            year: "2024",
            resolution: "tract",
            metricSet: "expanded",
            stateFips: "17",
            countyFips: "043",
            applyAdjustedAssumptions: true,
          },
          selection: {
            selectedGeoids: ["17043840100", "17043840200", "17043840300"],
            loadedRowCount: 3,
          },
          runtime: {
            statusText: "County profile refreshed.",
            aggregateRows: [
              { key: "population", value: 68420 },
              { key: "renters_pct", value: 0.29 },
            ],
            advisoryRows: [{ severity: "warn", text: "One tract has ACS margin > 8%." }],
          },
        },
        electionData: {
          revision: 8,
          import: {
            fileName: "dupage-2022-general.csv",
            importedAt: "2026-03-20T10:18:00.000Z",
            status: "imported",
            statusText: "Imported 3 rows.",
          },
          normalizedRows: [
            {
              state_fips: "17",
              county_fips: "043",
              election_date: "2022-11-08",
              office: "County Board",
              district_id: "D2",
              precinct_id: "043-002-001",
              candidate: "Marisol Reyes",
              candidate_id: "cand_reyes",
              party: "DEM",
              party_id: "dem",
              votes: 3012,
              total_votes_precinct: 5920,
              registered_voters: 8120,
            },
            {
              state_fips: "17",
              county_fips: "043",
              election_date: "2022-11-08",
              office: "County Board",
              district_id: "D2",
              precinct_id: "043-002-001",
              candidate: "David Holt",
              candidate_id: "cand_holt",
              party: "REP",
              party_id: "rep",
              votes: 2908,
              total_votes_precinct: 5920,
              registered_voters: 8120,
            },
            {
              state_fips: "17",
              county_fips: "043",
              election_date: "2020-11-03",
              office: "County Board",
              district_id: "D2",
              precinct_id: "043-002-002",
              candidate: "Marisol Reyes",
              candidate_id: "cand_reyes",
              party: "DEM",
              party_id: "dem",
              votes: 2741,
              total_votes_precinct: 5510,
              registered_voters: 7940,
            },
          ],
          benchmarks: {
            turnoutBaselines: [{ cycleYear: 2022, turnoutRate: 0.729 }],
            historicalRaceBenchmarks: [{ cycleYear: 2022, margin: 1.8 }],
            benchmarkSuggestions: [{ type: "county_turnout_floor", value: 0.68 }],
            downstreamRecommendations: {
              district: { baselineSupportHint: 0.504 },
              targeting: { turnoutBoostGeoids: ["043-002-001"] },
              outcome: { confidenceFloor: 0.58 },
            },
          },
        },
        targeting: {
          revision: 9,
          config: {
            geoLevel: "tract",
            modelId: "county_mix_v2",
            topN: 28,
            minScore: 0.44,
            onlyRaceFootprint: true,
          },
          runtime: {
            statusText: "County targeting complete.",
            lastRunAt: "2026-03-20T11:12:00.000Z",
            rows: [
              { geoid: "17043840100", score: 0.77, isTopTarget: true, reachableVoters: 1020, fieldEfficiency: 0.71 },
              { geoid: "17043840200", score: 0.69, isTopTarget: true, reachableVoters: 810, fieldEfficiency: 0.66 },
              { geoid: "17043840300", score: 0.58, isTopTarget: false, reachableVoters: 590, fieldEfficiency: 0.62 },
            ],
          },
        },
        outcome: {
          revision: 5,
          controls: {
            mcMode: "advanced",
            mcVolatility: "med",
          },
          cache: {
            mcLastHash: "mc_county_01",
            mcLast: {
              winProb: 0.52,
              expectedMargin: 0.4,
              p05Margin: -2.7,
              p95Margin: 3.6,
            },
            sensitivityRows: [{ label: "Persuasion conversion", impact: 0.27 }],
            surfaceRows: [{ x: 1.1, y: 0.95, winProb: 0.52 }],
            surfaceStatusText: "County surface ready.",
            surfaceSummaryText: "Toss-up contour remains.",
          },
        },
      },
    },
  },
  {
    id: "multi_candidate_primary",
    name: "Multi-candidate primary",
    nowIso: DEFAULT_GOLDEN_NOW_ISO,
    statePatch: {
      revision: 148,
      domains: {
        campaign: {
          campaignId: "il_sd_07_primary",
          campaignName: "Primary Coalition 7",
          officeId: "state_senate_07",
          scenarioName: "primary_multi_candidate",
        },
        district: {
          revision: 11,
          templateProfile: {
            raceType: "state_leg",
            officeLevel: "state",
            electionType: "primary",
            seatContext: "district",
            partisanshipMode: "same_party",
            salienceLevel: "high",
          },
          form: {
            electionDate: "2026-03-17",
            weeksRemaining: "7",
            mode: "persuasion",
            universeBasis: "registered",
            universeSize: 73000,
            turnoutA: 24,
            turnoutB: 36,
            bandWidth: 4,
          },
        },
        ballot: {
          yourCandidateId: "cand_chen",
          undecidedPct: 10,
          candidateRefs: {
            byId: {
              cand_chen: { id: "cand_chen", name: "Maya Chen", supportPct: 29 },
              cand_evans: { id: "cand_evans", name: "K. Evans", supportPct: 24 },
              cand_soto: { id: "cand_soto", name: "R. Soto", supportPct: 21 },
              cand_ellis: { id: "cand_ellis", name: "J. Ellis", supportPct: 16 },
            },
            order: ["cand_chen", "cand_evans", "cand_soto", "cand_ellis"],
          },
          userSplitByCandidateId: {
            cand_chen: 34,
            cand_evans: 26,
            cand_soto: 24,
            cand_ellis: 16,
          },
        },
        candidateHistory: {
          revision: 7,
          matchedRecordCount: 3,
          records: [
            {
              recordId: "hist_primary_2022",
              office: "State Senate 07",
              cycleYear: 2022,
              electionType: "primary",
              candidateName: "Maya Chen",
              party: "DEM",
              voteShare: 31.4,
              margin: 4.2,
              turnoutContext: 28.7,
              repeatCandidate: true,
              overUnderPerformancePct: 1.9,
            },
            {
              recordId: "hist_primary_2020",
              office: "State Senate 07",
              cycleYear: 2020,
              electionType: "primary",
              candidateName: "K. Evans",
              party: "DEM",
              voteShare: 26.1,
              margin: -1.1,
              turnoutContext: 26.3,
              repeatCandidate: true,
              overUnderPerformancePct: -0.7,
            },
            {
              recordId: "hist_primary_2018",
              office: "State Senate 07",
              cycleYear: 2018,
              electionType: "primary",
              candidateName: "R. Soto",
              party: "DEM",
              voteShare: 22.8,
              margin: -3.4,
              turnoutContext: 25,
              repeatCandidate: false,
              overUnderPerformancePct: -1.3,
            },
          ],
        },
        census: {
          revision: 9,
          config: {
            year: "2024",
            resolution: "block_group",
            metricSet: "expanded",
            stateFips: "17",
            countyFips: "031",
            applyAdjustedAssumptions: true,
          },
          selection: {
            selectedGeoids: ["170310501001", "170310501002", "170310501003", "170310501004"],
            loadedRowCount: 4,
          },
          runtime: {
            statusText: "Primary footprint loaded.",
            aggregateRows: [
              { key: "population", value: 48200 },
              { key: "young_voters_pct", value: 0.32 },
            ],
            advisoryRows: [{ severity: "warn", text: "Two BGs with sparse turnout history." }],
          },
        },
        electionData: {
          revision: 12,
          import: {
            fileName: "senate07-primary.csv",
            importedAt: "2026-03-20T09:40:00.000Z",
            status: "imported",
            statusText: "Imported 8 rows.",
          },
          normalizedRows: [
            {
              state_fips: "17",
              county_fips: "031",
              election_date: "2022-06-28",
              office: "State Senate",
              district_id: "07",
              precinct_id: "031-07-001",
              candidate: "Maya Chen",
              candidate_id: "cand_chen",
              party: "DEM",
              party_id: "dem",
              votes: 1430,
              total_votes_precinct: 5120,
              registered_voters: 9210,
            },
            {
              state_fips: "17",
              county_fips: "031",
              election_date: "2022-06-28",
              office: "State Senate",
              district_id: "07",
              precinct_id: "031-07-001",
              candidate: "K. Evans",
              candidate_id: "cand_evans",
              party: "DEM",
              party_id: "dem",
              votes: 1260,
              total_votes_precinct: 5120,
              registered_voters: 9210,
            },
            {
              state_fips: "17",
              county_fips: "031",
              election_date: "2022-06-28",
              office: "State Senate",
              district_id: "07",
              precinct_id: "031-07-001",
              candidate: "R. Soto",
              candidate_id: "cand_soto",
              party: "DEM",
              party_id: "dem",
              votes: 1110,
              total_votes_precinct: 5120,
              registered_voters: 9210,
            },
            {
              state_fips: "17",
              county_fips: "031",
              election_date: "2022-06-28",
              office: "State Senate",
              district_id: "07",
              precinct_id: "031-07-001",
              candidate: "J. Ellis",
              candidate_id: "cand_ellis",
              party: "DEM",
              party_id: "dem",
              votes: 920,
              total_votes_precinct: 5120,
              registered_voters: 9210,
            },
          ],
          qa: {
            sourceWarnings: ["One precinct had partial absentee detail."],
          },
          benchmarks: {
            turnoutBaselines: [{ cycleYear: 2022, turnoutRate: 0.556 }],
            historicalRaceBenchmarks: [{ cycleYear: 2022, margin: 3.3 }],
            comparableRacePools: [{ office: "State Senate", cycleYear: 2022, count: 17 }],
            benchmarkSuggestions: [{ type: "primary_turnout_floor", value: 0.31 }],
            downstreamRecommendations: {
              district: { baselineSupportHint: 0.287 },
              targeting: { turnoutBoostGeoids: ["031-07-001"] },
              outcome: { confidenceFloor: 0.46 },
            },
          },
        },
        targeting: {
          revision: 11,
          config: {
            geoLevel: "block_group",
            modelId: "primary_mix_v3",
            topN: 35,
            minScore: 0.39,
            onlyRaceFootprint: true,
          },
          runtime: {
            statusText: "Primary targeting complete.",
            lastRunAt: "2026-03-20T11:05:00.000Z",
            rows: [
              { geoid: "170310501001", score: 0.83, isTopTarget: true, reachableVoters: 660, fieldEfficiency: 0.76 },
              { geoid: "170310501002", score: 0.74, isTopTarget: true, reachableVoters: 580, fieldEfficiency: 0.73 },
              { geoid: "170310501003", score: 0.66, isTopTarget: true, reachableVoters: 510, fieldEfficiency: 0.69 },
              { geoid: "170310501004", score: 0.43, isTopTarget: false, reachableVoters: 320, fieldEfficiency: 0.57 },
            ],
          },
        },
        outcome: {
          revision: 8,
          controls: {
            mcMode: "advanced",
            mcVolatility: "high",
          },
          cache: {
            mcLastHash: "mc_primary_01",
            mcLast: {
              winProb: 0.41,
              expectedMargin: -0.9,
              p05Margin: -4.5,
              p95Margin: 2.1,
            },
            sensitivityRows: [
              { label: "Candidate consolidation", impact: 0.35 },
              { label: "Youth turnout", impact: 0.22 },
            ],
            surfaceRows: [{ x: 1.2, y: 0.9, winProb: 0.44 }],
            surfaceStatusText: "Primary surface ready.",
            surfaceSummaryText: "Fragmented field volatility dominates.",
          },
        },
      },
    },
  },
  {
    id: "low_data_race",
    name: "Low-data race",
    nowIso: DEFAULT_GOLDEN_NOW_ISO,
    statePatch: {
      revision: 62,
      domains: {
        campaign: {
          campaignId: "rural_board_5",
          campaignName: "Rural Outreach 5",
          officeId: "county_board_5",
          scenarioName: "low_data",
        },
        district: {
          revision: 3,
          templateProfile: {
            raceType: "county",
            officeLevel: "county",
            electionType: "general",
            seatContext: "district",
            partisanshipMode: "unknown",
            salienceLevel: "low",
          },
          form: {
            electionDate: "2026-11-03",
            weeksRemaining: "40",
            mode: "persuasion",
            universeBasis: "registered",
            universeSize: 22000,
            turnoutA: null,
            turnoutB: null,
            bandWidth: null,
          },
        },
        ballot: {
          yourCandidateId: "cand_a",
          undecidedPct: 30,
          candidateRefs: {
            byId: {
              cand_a: { id: "cand_a", name: "Candidate A", supportPct: 35 },
              cand_b: { id: "cand_b", name: "Candidate B", supportPct: 35 },
            },
            order: ["cand_a", "cand_b"],
          },
          userSplitByCandidateId: {
            cand_a: null,
            cand_b: null,
          },
        },
        candidateHistory: {
          revision: 1,
          matchedRecordCount: 0,
          records: [],
        },
        census: {
          revision: 2,
          config: {
            year: "2024",
            resolution: "tract",
            metricSet: "core",
            stateFips: "17",
            countyFips: "000",
            applyAdjustedAssumptions: false,
          },
          selection: {
            selectedGeoids: [],
            loadedRowCount: 0,
          },
          runtime: {
            statusText: "Awaiting census import.",
            aggregateRows: [],
            advisoryRows: [{ severity: "warn", text: "No tract-level data loaded." }],
          },
        },
        electionData: {
          revision: 2,
          import: {
            fileName: "",
            importedAt: "",
            status: "error",
            statusText: "No valid election rows imported.",
          },
          normalizedRows: [],
          qa: {
            errors: ["Missing required columns: precinct_id,votes"],
          },
          benchmarks: {
            turnoutBaselines: [],
            historicalRaceBenchmarks: [],
            comparableRacePools: [],
            benchmarkSuggestions: [],
            downstreamRecommendations: {
              district: {},
              targeting: {},
              outcome: {},
            },
          },
        },
        targeting: {
          revision: 2,
          config: {
            geoLevel: "tract",
            modelId: "turnout_opportunity",
            topN: 20,
            minScore: 0.35,
            onlyRaceFootprint: true,
          },
          runtime: {
            statusText: "Awaiting upstream data.",
            lastRunAt: "",
            rows: [],
          },
        },
        outcome: {
          revision: 1,
          controls: {
            mcMode: "basic",
            mcVolatility: "med",
          },
          cache: {
            mcLastHash: "",
            mcLast: null,
            sensitivityRows: [],
            surfaceRows: [],
            surfaceStatusText: "No outcome run yet.",
            surfaceSummaryText: "Awaiting data.",
          },
        },
      },
    },
  },
  {
    id: "election_data_imported",
    name: "Election data imported and propagated",
    nowIso: DEFAULT_GOLDEN_NOW_ISO,
    statePatch: {
      revision: 174,
      domains: {
        campaign: {
          campaignId: "il_hd_44",
          campaignName: "House 44 Growth",
          officeId: "state_house_44",
          scenarioName: "election_data_calibrated",
        },
        district: {
          revision: 13,
          templateProfile: {
            raceType: "state_leg",
            officeLevel: "state",
            electionType: "general",
            seatContext: "district",
            partisanshipMode: "swing",
            salienceLevel: "high",
          },
          form: {
            electionDate: "2026-11-03",
            weeksRemaining: "29",
            mode: "persuasion",
            universeBasis: "registered",
            universeSize: 118000,
            turnoutA: 43,
            turnoutB: 58,
            bandWidth: 5,
          },
        },
        ballot: {
          yourCandidateId: "cand_nguyen",
          undecidedPct: 8,
          candidateRefs: {
            byId: {
              cand_nguyen: { id: "cand_nguyen", name: "Linh Nguyen", supportPct: 49 },
              cand_miller: { id: "cand_miller", name: "Sam Miller", supportPct: 43 },
            },
            order: ["cand_nguyen", "cand_miller"],
          },
          userSplitByCandidateId: {
            cand_nguyen: 55,
            cand_miller: 45,
          },
        },
        candidateHistory: {
          revision: 8,
          matchedRecordCount: 3,
          records: [
            {
              recordId: "hist_hd44_2024",
              office: "State House 44",
              cycleYear: 2024,
              electionType: "general",
              candidateName: "Linh Nguyen",
              party: "DEM",
              voteShare: 51.8,
              margin: 3.7,
              turnoutContext: 63.1,
              repeatCandidate: true,
              overUnderPerformancePct: 1.6,
            },
            {
              recordId: "hist_hd44_2022",
              office: "State House 44",
              cycleYear: 2022,
              electionType: "general",
              candidateName: "Sam Miller",
              party: "REP",
              voteShare: 48.2,
              margin: -3.7,
              turnoutContext: 58.4,
              repeatCandidate: false,
              overUnderPerformancePct: -1.2,
            },
          ],
        },
        census: {
          revision: 10,
          config: {
            year: "2024",
            resolution: "tract",
            metricSet: "expanded",
            stateFips: "17",
            countyFips: "111",
            applyAdjustedAssumptions: true,
          },
          selection: {
            selectedGeoids: ["17111010100", "17111010200", "17111010300"],
            loadedRowCount: 3,
          },
          runtime: {
            statusText: "Census profile ready.",
            aggregateRows: [
              { key: "population", value: 88400 },
              { key: "bachelor_pct", value: 0.42 },
            ],
            advisoryRows: [],
          },
        },
        electionData: {
          revision: 15,
          import: {
            fileName: "hd44-history.csv",
            importedAt: "2026-03-20T08:55:00.000Z",
            status: "imported",
            statusText: "Imported 6 rows.",
          },
          normalizedRows: [
            {
              state_fips: "17",
              county_fips: "111",
              election_date: "2024-11-05",
              office: "State House",
              district_id: "44",
              precinct_id: "111-044-001",
              candidate: "Linh Nguyen",
              candidate_id: "cand_nguyen",
              party: "DEM",
              party_id: "dem",
              votes: 4320,
              total_votes_precinct: 8420,
              registered_voters: 12400,
            },
            {
              state_fips: "17",
              county_fips: "111",
              election_date: "2024-11-05",
              office: "State House",
              district_id: "44",
              precinct_id: "111-044-001",
              candidate: "Sam Miller",
              candidate_id: "cand_miller",
              party: "REP",
              party_id: "rep",
              votes: 4100,
              total_votes_precinct: 8420,
              registered_voters: 12400,
            },
            {
              state_fips: "17",
              county_fips: "111",
              election_date: "2022-11-08",
              office: "State House",
              district_id: "44",
              precinct_id: "111-044-002",
              candidate: "Linh Nguyen",
              candidate_id: "cand_nguyen",
              party: "DEM",
              party_id: "dem",
              votes: 3988,
              total_votes_precinct: 7910,
              registered_voters: 11880,
            },
            {
              state_fips: "17",
              county_fips: "111",
              election_date: "2022-11-08",
              office: "State House",
              district_id: "44",
              precinct_id: "111-044-002",
              candidate: "Sam Miller",
              candidate_id: "cand_miller",
              party: "REP",
              party_id: "rep",
              votes: 3922,
              total_votes_precinct: 7910,
              registered_voters: 11880,
            },
          ],
          qa: {
            sourceWarnings: [],
            geographyWarnings: [],
            candidateWarnings: [],
            mappingWarnings: [],
            errors: [],
          },
          benchmarks: {
            turnoutBaselines: [{ cycleYear: 2024, turnoutRate: 0.679 }],
            historicalRaceBenchmarks: [
              { cycleYear: 2024, margin: 0.8 },
              { cycleYear: 2022, margin: 0.4 },
            ],
            volatilityBands: [{ metric: "margin", low: -1.2, high: 1.4 }],
            partyBaselineContext: [{ party: "DEM", avgShare: 0.506 }],
            comparableRacePools: [{ office: "State House", cycleYear: 2024, count: 29 }],
            repeatCandidatePerformance: [{ candidate: "Linh Nguyen", overUnderPerformancePct: 1.6 }],
            precinctPerformanceDistributions: [{ percentile: "p50", margin: 0.9 }],
            geographyRollups: [{ level: "district", margin: 0.8 }],
            benchmarkSuggestions: [
              { type: "baseline_support", value: 0.507 },
              { type: "turnout_floor", value: 0.66 },
            ],
            downstreamRecommendations: {
              district: { baselineSupportHint: 0.507, turnoutCalibration: 0.66 },
              targeting: { turnoutBoostGeoids: ["111-044-001", "111-044-002"], minScoreHint: 0.41 },
              outcome: { confidenceFloor: 0.63, volatilityOverride: "medium" },
            },
          },
        },
        targeting: {
          revision: 14,
          config: {
            geoLevel: "tract",
            modelId: "house_general_v4",
            topN: 40,
            minScore: 0.41,
            onlyRaceFootprint: true,
          },
          runtime: {
            statusText: "Targeting calibrated by election history.",
            lastRunAt: "2026-03-20T11:30:00.000Z",
            rows: [
              { geoid: "17111010100", score: 0.82, isTopTarget: true, reachableVoters: 1190, fieldEfficiency: 0.77 },
              { geoid: "17111010200", score: 0.75, isTopTarget: true, reachableVoters: 980, fieldEfficiency: 0.71 },
              { geoid: "17111010300", score: 0.63, isTopTarget: false, reachableVoters: 720, fieldEfficiency: 0.64 },
            ],
          },
        },
        outcome: {
          revision: 10,
          controls: {
            mcMode: "advanced",
            mcVolatility: "med",
          },
          cache: {
            mcLastHash: "mc_hd44_01",
            mcLast: {
              winProb: 0.61,
              expectedMargin: 1.9,
              p05Margin: -1.2,
              p95Margin: 4.8,
            },
            sensitivityRows: [
              { label: "Turnout floor", impact: 0.3 },
              { label: "Persuasion contact rate", impact: 0.2 },
            ],
            surfaceRows: [{ x: 1, y: 1, winProb: 0.61 }],
            surfaceStatusText: "Outcome surface ready.",
            surfaceSummaryText: "Positive baseline with narrow risk band.",
          },
        },
      },
    },
  },
  {
    id: "war_room_active",
    name: "War room active scenario",
    nowIso: DEFAULT_GOLDEN_NOW_ISO,
    statePatch: {
      revision: 189,
      domains: {
        campaign: {
          campaignId: "citywide_mayor",
          campaignName: "Citywide Ops",
          officeId: "mayor_city",
          scenarioName: "war_room_active",
        },
        district: {
          revision: 10,
          templateProfile: {
            raceType: "municipal",
            officeLevel: "city",
            electionType: "general",
            seatContext: "citywide",
            partisanshipMode: "nonpartisan",
            salienceLevel: "high",
          },
          form: {
            electionDate: "2026-11-03",
            weeksRemaining: "20",
            mode: "turnout",
            universeBasis: "registered",
            universeSize: 240000,
            turnoutA: 37,
            turnoutB: 52,
            bandWidth: 5,
          },
        },
        ballot: {
          yourCandidateId: "cand_ada",
          undecidedPct: 10,
          candidateRefs: {
            byId: {
              cand_ada: { id: "cand_ada", name: "Ada Flores", supportPct: 46 },
              cand_brown: { id: "cand_brown", name: "T. Brown", supportPct: 44 },
            },
            order: ["cand_ada", "cand_brown"],
          },
          userSplitByCandidateId: {
            cand_ada: 54,
            cand_brown: 46,
          },
        },
        weatherRisk: {
          revision: 6,
          officeZip: "60602",
          overrideZip: "60610",
          useOverrideZip: true,
          selectedZip: "60610",
          status: "ready",
          fetchedAt: "2026-03-20T11:44:00.000Z",
          current: {
            tempF: 39,
            windMph: 22,
            precipType: "rain",
          },
          forecast3d: [
            { day: "2026-03-21", precipProbability: 0.72 },
            { day: "2026-03-22", precipProbability: 0.48 },
            { day: "2026-03-23", precipProbability: 0.21 },
          ],
          fieldExecutionRisk: "high",
          electionDayTurnoutRisk: "medium",
          recommendedAction: "Shift heavy turf to call/text coverage for 24h.",
          precipSignal: 0.67,
          adjustment: {
            enabled: true,
            mode: "observe_only",
            date: "2026-03-21",
            zip: "60610",
            modifiers: {
              doorEfficiencyMultiplier: 0.76,
              volunteerShowRateMultiplier: 0.84,
              electionDayTurnoutRiskBump: 0.09,
            },
            appliedAt: "2026-03-20T11:46:00.000Z",
            log: [
              { at: "2026-03-20T11:45:00.000Z", type: "advisory", note: "Rain front approaching." },
              { at: "2026-03-20T11:46:00.000Z", type: "ops", note: "Rebalanced weekend shifts." },
            ],
          },
        },
        eventCalendar: {
          revision: 8,
          filters: {
            category: "all",
            date: "",
            includeInactive: false,
            appliedOnly: false,
          },
          events: [
            {
              eventId: "evt_1",
              title: "Weekend canvass launch",
              category: "field",
              date: "2026-03-21",
              status: "scheduled",
              applyToModel: true,
            },
            {
              eventId: "evt_2",
              title: "Rapid weather standup",
              category: "ops",
              date: "2026-03-21",
              status: "scheduled",
              applyToModel: true,
            },
            {
              eventId: "evt_3",
              title: "Volunteer SMS fallback push",
              category: "digital",
              date: "2026-03-22",
              status: "closed",
              applyToModel: false,
            },
          ],
        },
        targeting: {
          revision: 10,
          config: {
            geoLevel: "block_group",
            modelId: "city_ops_v1",
            topN: 50,
            minScore: 0.43,
            onlyRaceFootprint: true,
          },
          runtime: {
            statusText: "Targeting refreshed with weather offsets.",
            lastRunAt: "2026-03-20T11:50:00.000Z",
            rows: [
              { geoid: "170319801001", score: 0.81, isTopTarget: true, reachableVoters: 1420, fieldEfficiency: 0.72 },
              { geoid: "170319801002", score: 0.73, isTopTarget: true, reachableVoters: 1330, fieldEfficiency: 0.67 },
              { geoid: "170319801003", score: 0.55, isTopTarget: false, reachableVoters: 910, fieldEfficiency: 0.58 },
            ],
          },
        },
        outcome: {
          revision: 9,
          controls: {
            mcMode: "advanced",
            mcVolatility: "high",
          },
          cache: {
            mcLastHash: "mc_warroom_01",
            mcLast: {
              winProb: 0.54,
              expectedMargin: 0.8,
              p05Margin: -2.9,
              p95Margin: 4.1,
            },
            sensitivityRows: [
              { label: "Weather-adjusted field efficiency", impact: 0.34 },
              { label: "Volunteer attendance", impact: 0.28 },
            ],
            surfaceRows: [{ x: 0.85, y: 1.2, winProb: 0.53 }],
            surfaceStatusText: "War room surface ready.",
            surfaceSummaryText: "Weather exposure is principal risk.",
          },
        },
      },
    },
  },
  {
    id: "archive_recovery_reporting_history",
    name: "Archive, recovery, and reporting history",
    nowIso: DEFAULT_GOLDEN_NOW_ISO,
    statePatch: {
      revision: 205,
      domains: {
        campaign: {
          campaignId: "county_exec_01",
          campaignName: "County Executive Forward",
          officeId: "county_exec",
          scenarioName: "history_loaded",
        },
        district: {
          revision: 8,
          templateProfile: {
            raceType: "county",
            officeLevel: "county",
            electionType: "general",
            seatContext: "countywide",
            partisanshipMode: "swing",
            salienceLevel: "high",
          },
          form: {
            electionDate: "2026-11-03",
            weeksRemaining: "24",
            mode: "persuasion",
            universeBasis: "registered",
            universeSize: 182000,
            turnoutA: 40,
            turnoutB: 57,
            bandWidth: 6,
          },
        },
        ballot: {
          yourCandidateId: "cand_patel",
          undecidedPct: 9,
          candidateRefs: {
            byId: {
              cand_patel: { id: "cand_patel", name: "N. Patel", supportPct: 47 },
              cand_taylor: { id: "cand_taylor", name: "J. Taylor", supportPct: 44 },
            },
            order: ["cand_patel", "cand_taylor"],
          },
          userSplitByCandidateId: {
            cand_patel: 53,
            cand_taylor: 47,
          },
        },
        electionData: {
          revision: 11,
          import: {
            fileName: "county_exec_history.csv",
            importedAt: "2026-03-19T15:30:00.000Z",
            status: "imported",
            statusText: "Imported 4 rows.",
          },
          normalizedRows: [
            {
              state_fips: "17",
              county_fips: "197",
              election_date: "2024-11-05",
              office: "County Executive",
              district_id: "countywide",
              precinct_id: "197-000-001",
              candidate: "N. Patel",
              candidate_id: "cand_patel",
              party: "DEM",
              party_id: "dem",
              votes: 18840,
              total_votes_precinct: 37200,
              registered_voters: 51100,
            },
            {
              state_fips: "17",
              county_fips: "197",
              election_date: "2024-11-05",
              office: "County Executive",
              district_id: "countywide",
              precinct_id: "197-000-001",
              candidate: "J. Taylor",
              candidate_id: "cand_taylor",
              party: "REP",
              party_id: "rep",
              votes: 18360,
              total_votes_precinct: 37200,
              registered_voters: 51100,
            },
          ],
          benchmarks: {
            turnoutBaselines: [{ cycleYear: 2024, turnoutRate: 0.728 }],
            historicalRaceBenchmarks: [{ cycleYear: 2024, margin: 0.6 }],
            benchmarkSuggestions: [{ type: "confidence_floor", value: 0.6 }],
            downstreamRecommendations: {
              district: { baselineSupportHint: 0.503 },
              targeting: { turnoutBoostGeoids: ["197-000-001"] },
              outcome: { confidenceFloor: 0.6 },
            },
          },
        },
        targeting: {
          revision: 8,
          config: {
            geoLevel: "tract",
            modelId: "county_exec_v2",
            topN: 45,
            minScore: 0.42,
            onlyRaceFootprint: true,
          },
          runtime: {
            statusText: "Targeting synced from archive context.",
            lastRunAt: "2026-03-20T09:15:00.000Z",
            rows: [
              { geoid: "17197010100", score: 0.74, isTopTarget: true, reachableVoters: 1670, fieldEfficiency: 0.69 },
              { geoid: "17197010200", score: 0.66, isTopTarget: true, reachableVoters: 1490, fieldEfficiency: 0.63 },
              { geoid: "17197010300", score: 0.52, isTopTarget: false, reachableVoters: 1220, fieldEfficiency: 0.57 },
            ],
          },
        },
        outcome: {
          revision: 8,
          controls: {
            mcMode: "advanced",
            mcVolatility: "med",
          },
          cache: {
            mcLastHash: "mc_archive_01",
            mcLast: {
              winProb: 0.55,
              expectedMargin: 1.1,
              p05Margin: -2.1,
              p95Margin: 4.2,
            },
            sensitivityRows: [{ label: "Archive-adjusted trendline", impact: 0.25 }],
            surfaceRows: [{ x: 1.05, y: 0.95, winProb: 0.55 }],
            surfaceStatusText: "Archive surface ready.",
            surfaceSummaryText: "Trendline stabilized by recent actuals.",
          },
        },
        forecastArchive: {
          selectedHash: "snap_2026w11",
          entries: [
            {
              snapshotHash: "snap_2026w11",
              recordedAt: "2026-03-18T22:10:00.000Z",
              expectedMargin: 1.1,
              winProb: 0.55,
            },
            {
              snapshotHash: "snap_2026w10",
              recordedAt: "2026-03-11T22:04:00.000Z",
              expectedMargin: 0.7,
              winProb: 0.52,
            },
          ],
          summary: {
            total: 2,
            staleCount: 0,
            latestAt: "2026-03-18T22:10:00.000Z",
          },
        },
        recovery: {
          strictImport: true,
          usbConnected: true,
          lastBackupRestoreAt: "2026-03-19T07:32:00.000Z",
          lastImportFileName: "county_exec_recovery_20260319.json",
          lastWarning: "Recovered from local backup after export mismatch.",
          lastHashBanner: "hash:9bc88f",
        },
        governance: {
          snapshot: {
            confidenceBand: "MEDIUM",
            topWarning: "Volunteer conversion is below plan.",
            learningRecommendation: "Increase call follow-up in low-response tracts.",
          },
          confidenceBand: "MEDIUM",
          topWarning: "Volunteer conversion is below plan.",
          learningRecommendation: "Increase call follow-up in low-response tracts.",
        },
        scenarios: {
          activeScenarioId: "baseline",
          selectedScenarioId: "weekly_refresh",
          records: {
            baseline: { id: "baseline", label: "Baseline" },
            weekly_refresh: { id: "weekly_refresh", label: "Weekly Refresh" },
          },
          decisionSessions: {
            "2026-03-18": {
              id: "2026-03-18",
              title: "Ops/field sync",
              owner: "Director",
            },
          },
        },
        audit: {
          validationSnapshot: {
            status: "warn",
            messages: ["Targeting refresh lagged by one run."],
          },
          realismSnapshot: {
            confidence: 0.68,
            note: "Execution assumptions moderately realistic.",
          },
          diagnosticsSnapshot: {
            drift: "moderate",
            bottleneck: "volunteers",
          },
          contractFindings: [
            { id: "finding_1", severity: "warn", text: "One archive entry missing metadata." },
          ],
        },
      },
    },
  },
];
